//! Orchestrate file emission for the tower-based Rust client.
//!
//! Always emits a module tree at the output root (no Cargo.toml — the
//! consumer drops it into an existing crate as `pub mod gen;`). The shape:
//!
//! ```text
//! <out>/
//! ├── mod.rs                 # declares submodules, re-exports runtime entrypoints
//! ├── runtime.rs             # Operation trait + execute helper
//! ├── models.rs              # serde structs/enums for named types
//! └── operations/
//!     ├── mod.rs             # `pub mod <op>;` per kept op
//!     └── <snake>.rs         # request struct + Output + Error + impl Operation
//! ```

use forge_plugin_sdk::ir;
use forge_plugin_sdk::{FileMode, GenerationOutput, OutputFile};

use crate::models;
use crate::naming;
use crate::operation_impl;

const MOD_RS: &str = include_str!("../templates/mod.rs.in");
const RUNTIME_RS: &str = include_str!("../templates/runtime.rs.in");

pub fn all(spec: &ir::Ir) -> GenerationOutput {
    let mut files = vec![
        OutputFile {
            path: "mod.rs".into(),
            content: MOD_RS.as_bytes().to_vec(),
            mode: FileMode::Text,
        },
        OutputFile {
            path: "runtime.rs".into(),
            content: RUNTIME_RS.as_bytes().to_vec(),
            mode: FileMode::Text,
        },
        OutputFile {
            path: "models.rs".into(),
            content: models::render(spec).into_bytes(),
            mode: FileMode::Text,
        },
    ];

    let mut operations_mod = String::new();
    operations_mod.push_str("// Generated by openapi-forge — do not edit by hand.\n\n");
    operations_mod.push_str("#![allow(unused_imports)]\n\n");
    for op in &spec.operations {
        let snake = naming::snake_case(&op.id);
        operations_mod.push_str(&format!("pub mod {snake};\n"));
    }

    files.push(OutputFile {
        path: "operations/mod.rs".into(),
        content: operations_mod.into_bytes(),
        mode: FileMode::Text,
    });

    for op in &spec.operations {
        let snake = naming::snake_case(&op.id);
        files.push(OutputFile {
            path: format!("operations/{snake}.rs"),
            content: operation_impl::render(spec, op).into_bytes(),
            mode: FileMode::Text,
        });
    }

    GenerationOutput {
        files,
        diagnostics: Vec::new(),
    }
}
