//! Emit `models.rs`: one `#[derive(Serialize, Deserialize)]` definition per
//! `NamedType` in the (filtered) IR. Objects become structs, string enums
//! become Rust enums, int enums become enums backed by `i64`. Everything else
//! (unions, primitives, null) lands as a type alias or falls back to
//! `serde_json::Value` with a `// TODO`.

use forge_plugin_sdk::ir;

use crate::naming;
use crate::types::type_ref_to_rust;

/// From inside `models.rs`, sibling named types resolve by bare name. We
/// pass an empty path prefix to `type_ref_to_rust`, which yields
/// `::Foo` — strip the leading `::` before placing in the output.
const MODELS_PATH_INSIDE: &str = "";

pub fn render(spec: &ir::Ir) -> String {
    let mut s = String::new();
    s.push_str("// Generated by openapi-forge — do not edit by hand.\n\n");
    s.push_str("#![allow(non_snake_case, non_camel_case_types, clippy::all, clippy::pedantic, clippy::nursery, dead_code)]\n\n");
    s.push_str("use serde::{Deserialize, Serialize};\n\n");
    for named in &spec.types {
        if named.id == ir::NULL_ID {
            continue;
        }
        render_named(&mut s, spec, named);
        s.push('\n');
    }
    s
}

fn render_named(out: &mut String, spec: &ir::Ir, named: &ir::NamedType) {
    let name = naming::rust_type_name(named);
    if let Some(doc) = &named.documentation {
        for line in doc.lines() {
            out.push_str("/// ");
            out.push_str(line);
            out.push('\n');
        }
    }
    match &named.definition {
        ir::TypeDef::Object(o) => render_struct(out, spec, &name, o),
        ir::TypeDef::EnumString(e) => render_string_enum(out, &name, e),
        ir::TypeDef::EnumInt(e) => render_int_enum(out, &name, e),
        ir::TypeDef::Primitive(p) => {
            out.push_str(&format!(
                "pub type {name} = {};\n",
                crate::types::type_ref_to_rust(spec, &named.id, MODELS_PATH_INSIDE,).replace(
                    &format!("{MODELS_PATH_INSIDE}::{name}"),
                    &super_primitive(p)
                )
            ));
        }
        ir::TypeDef::Array(_) | ir::TypeDef::Union(_) => {
            // Inline → emit as alias.
            let rhs = type_ref_to_rust(spec, &named.id, MODELS_PATH_INSIDE);
            out.push_str(&format!("pub type {name} = {rhs};\n"));
        }
        ir::TypeDef::Null => {}
    }
}

fn super_primitive(p: &ir::PrimitiveType) -> String {
    // Used only for the alias rendering path above; mirror types.rs.
    match p.kind {
        ir::PrimitiveKind::String => "String".to_string(),
        ir::PrimitiveKind::Integer => "i64".to_string(),
        ir::PrimitiveKind::Number => "f64".to_string(),
        ir::PrimitiveKind::Bool => "bool".to_string(),
    }
}

fn render_struct(out: &mut String, spec: &ir::Ir, name: &str, o: &ir::ObjectType) {
    out.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
    if o.properties.is_empty()
        && matches!(o.additional_properties, ir::AdditionalProperties::Forbidden)
    {
        out.push_str(&format!("pub struct {name} {{}}\n"));
        return;
    }
    out.push_str(&format!("pub struct {name} {{\n"));
    for prop in &o.properties {
        if let Some(doc) = &prop.documentation {
            for line in doc.lines() {
                out.push_str("    /// ");
                out.push_str(line);
                out.push('\n');
            }
        }
        let rust_name = naming::snake_case(&prop.name);
        let rename_needed = strip_raw(&rust_name) != prop.name;
        let inner_ty = type_ref_to_rust(spec, &prop.r#type, MODELS_PATH_INSIDE);
        let (final_ty, needs_skip) = if prop.required {
            (inner_ty, false)
        } else if inner_ty.starts_with("Option<") {
            (inner_ty, true)
        } else {
            (format!("Option<{inner_ty}>"), true)
        };
        if rename_needed {
            out.push_str(&format!(
                "    #[serde(rename = \"{}\")]\n",
                naming::escape_str(&prop.name)
            ));
        }
        if needs_skip {
            out.push_str("    #[serde(default, skip_serializing_if = \"Option::is_none\")]\n");
        }
        out.push_str(&format!("    pub {rust_name}: {final_ty},\n"));
    }
    if let ir::AdditionalProperties::Typed { r#type } = &o.additional_properties {
        let inner = type_ref_to_rust(spec, r#type, MODELS_PATH_INSIDE);
        out.push_str("    #[serde(flatten)]\n");
        out.push_str(&format!(
            "    pub additional: std::collections::HashMap<String, {inner}>,\n"
        ));
    }
    out.push_str("}\n");
}

fn render_string_enum(out: &mut String, name: &str, e: &ir::EnumStringType) {
    out.push_str("#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]\n");
    out.push_str(&format!("pub enum {name} {{\n"));
    for value in &e.values {
        let variant = naming::pascal_case(&value.value);
        if let Some(doc) = &value.documentation {
            for line in doc.lines() {
                out.push_str("    /// ");
                out.push_str(line);
                out.push('\n');
            }
        }
        if strip_raw(&naming::snake_case(&variant)) != value.value
            || !value
                .value
                .chars()
                .all(|c| c.is_ascii_alphanumeric() || c == '_')
        {
            out.push_str(&format!(
                "    #[serde(rename = \"{}\")]\n",
                naming::escape_str(&value.value)
            ));
        }
        out.push_str(&format!("    {variant},\n"));
    }
    out.push_str("}\n");
}

fn render_int_enum(out: &mut String, name: &str, e: &ir::EnumIntType) {
    // serde-tagged repr matches the wire form. We don't try to derive
    // `Copy` even for int enums — adding it would constrain future
    // additions, and the cost of a `.clone()` is nothing.
    out.push_str("#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]\n");
    out.push_str("#[serde(into = \"i64\", try_from = \"i64\")]\n");
    out.push_str(&format!("pub enum {name} {{\n"));
    for value in &e.values {
        if let Some(doc) = &value.documentation {
            for line in doc.lines() {
                out.push_str("    /// ");
                out.push_str(line);
                out.push('\n');
            }
        }
        out.push_str(&format!("    V{},\n", value.value.abs()));
    }
    out.push_str("}\n\n");
    out.push_str(&format!("impl From<{name}> for i64 {{\n"));
    out.push_str(&format!("    fn from(v: {name}) -> i64 {{\n"));
    out.push_str("        match v {\n");
    for value in &e.values {
        out.push_str(&format!(
            "            {name}::V{} => {},\n",
            value.value.abs(),
            value.value
        ));
    }
    out.push_str("        }\n    }\n}\n\n");
    out.push_str(&format!("impl std::convert::TryFrom<i64> for {name} {{\n"));
    out.push_str("    type Error = String;\n");
    out.push_str("    fn try_from(v: i64) -> Result<Self, Self::Error> {\n");
    out.push_str("        match v {\n");
    for value in &e.values {
        out.push_str(&format!(
            "            {} => Ok({name}::V{}),\n",
            value.value,
            value.value.abs()
        ));
    }
    out.push_str(&format!(
        "            other => Err(format!(\"unknown {name} discriminant: {{}}\", other)),\n"
    ));
    out.push_str("        }\n    }\n}\n");
}

fn strip_raw(s: &str) -> &str {
    s.strip_prefix("r#").unwrap_or(s)
}
