//! Per-operation rendering.
//!
//! For each `Operation` we emit a small module containing:
//!  - a request struct holding path/query/header params + body
//!  - an `Output` enum with one variant per declared status code
//!  - an `Error` enum (`Undeclared { status, body }`, decode failures, build failures)
//!  - `impl crate::Operation for <op>`
//!
//! The trait's `parse_response` is the only thing with hairy bounds; the
//! actual `match status { … }` inside is mechanical.

use forge_plugin_sdk::ir;

use crate::naming;
use crate::types::type_ref_to_rust;

const MODELS_PATH: &str = "super::super::models";

pub fn render(spec: &ir::Ir, op: &ir::Operation) -> String {
    let struct_name = naming::pascal_case(&op.id);
    let output_name = format!("{struct_name}Output");
    let error_name = format!("{struct_name}Error");

    let mut s = String::new();
    s.push_str("// Generated by openapi-forge — do not edit by hand.\n\n");
    s.push_str("#![allow(non_snake_case, non_camel_case_types, clippy::all, unused_imports, unused_mut, dead_code)]\n\n");
    s.push_str("use super::super::runtime;\n");
    s.push_str("use serde::{Deserialize, Serialize};\n\n");

    render_request_struct(&mut s, spec, op, &struct_name);
    render_output_enum(&mut s, spec, op, &output_name);
    render_error_enum(&mut s, &error_name);
    render_operation_impl(&mut s, spec, op, &struct_name, &output_name, &error_name);

    s
}

fn render_request_struct(out: &mut String, spec: &ir::Ir, op: &ir::Operation, name: &str) {
    if let Some(doc) = &op.documentation {
        for line in doc.lines() {
            out.push_str("/// ");
            out.push_str(line);
            out.push('\n');
        }
    }
    out.push_str("#[derive(Debug, Clone)]\n");
    out.push_str(&format!("pub struct {name} {{\n"));
    for p in &op.path_params {
        // Path params are always `String` regardless of the spec's declared
        // type. They get stringified into the URL via `format!`; accepting
        // `String` is far more ergonomic than forcing the caller to hand
        // the generated code an `f64` for a campaignId.
        let field = naming::snake_case(&p.name);
        out.push_str(&format!("    pub {field}: String,\n"));
    }
    for p in &op.query_params {
        let field = naming::snake_case(&p.name);
        let ty = type_ref_to_rust(spec, &p.r#type, MODELS_PATH);
        let final_ty = if p.required {
            ty
        } else {
            format!("Option<{ty}>")
        };
        out.push_str(&format!("    pub {field}: {final_ty},\n"));
    }
    for p in &op.header_params {
        let field = naming::snake_case(&p.name);
        let ty = type_ref_to_rust(spec, &p.r#type, MODELS_PATH);
        let final_ty = if p.required {
            ty
        } else {
            format!("Option<{ty}>")
        };
        out.push_str(&format!("    pub {field}: {final_ty},\n"));
    }
    if let Some(body) = &op.request_body {
        // We pick the first `application/json` body; multipart / form-data /
        // binary fall back to `serde_json::Value` with a TODO note. The
        // dialai use case only hits JSON, so anything else just doesn't
        // exercise this path.
        if let Some(json) = body
            .content
            .iter()
            .find(|c| c.media_type == "application/json")
        {
            let ty = type_ref_to_rust(spec, &json.r#type, MODELS_PATH);
            let final_ty = if body.required {
                ty
            } else {
                format!("Option<{ty}>")
            };
            out.push_str(&format!("    pub body: {final_ty},\n"));
        } else {
            out.push_str("    // TODO non-JSON request body — falling back to serde_json::Value\n");
            out.push_str("    pub body: serde_json::Value,\n");
        }
    }
    out.push_str("}\n\n");
}

fn render_output_enum(out: &mut String, spec: &ir::Ir, op: &ir::Operation, name: &str) {
    out.push_str("#[derive(Debug)]\n");
    out.push_str(&format!("pub enum {name} {{\n"));
    if op.responses.is_empty() {
        out.push_str("    /// Spec declared no responses; treat any 2xx as success.\n");
        out.push_str("    Success,\n");
    } else {
        for resp in &op.responses {
            let variant = status_variant(&resp.status);
            let body = pick_json_response_body(resp);
            match body {
                Some(type_ref) => {
                    let ty = type_ref_to_rust(spec, type_ref, MODELS_PATH);
                    out.push_str(&format!("    {variant}({ty}),\n"));
                }
                None => out.push_str(&format!("    {variant},\n")),
            }
        }
    }
    out.push_str("}\n\n");
}

fn render_error_enum(out: &mut String, name: &str) {
    out.push_str("#[derive(Debug, thiserror::Error)]\n");
    out.push_str(&format!("pub enum {name} {{\n"));
    out.push_str("    #[error(\"undeclared status {status}: {body}\")]\n");
    out.push_str("    UndeclaredStatus { status: u16, body: String },\n");
    out.push_str("    #[error(\"json decode error: {0}\")]\n");
    out.push_str("    Decode(#[from] serde_json::Error),\n");
    out.push_str("    #[error(\"response body collection failed: {0}\")]\n");
    out.push_str("    Body(Box<dyn std::error::Error + Send + Sync>),\n");
    out.push_str("    #[error(\"http builder error: {0}\")]\n");
    out.push_str("    HttpBuild(#[from] http::Error),\n");
    out.push_str("}\n\n");
}

fn render_operation_impl(
    out: &mut String,
    spec: &ir::Ir,
    op: &ir::Operation,
    struct_name: &str,
    output_name: &str,
    error_name: &str,
) {
    out.push_str(&format!("impl runtime::Operation for {struct_name} {{\n"));
    out.push_str("    type RequestBody = http_body_util::Full<bytes::Bytes>;\n");
    out.push_str(&format!("    type Output = {output_name};\n"));
    out.push_str(&format!("    type Error = {error_name};\n\n"));
    out.push_str(&format!(
        "    const METHOD: http::Method = http::Method::{};\n",
        op.method.as_str()
    ));
    out.push_str(&format!(
        "    const PATH_TEMPLATE: &'static str = \"{}\";\n",
        naming::escape_str(&op.path_template)
    ));
    let op_id = op.original_id.as_deref().unwrap_or(&op.id);
    out.push_str(&format!(
        "    const OPERATION_ID: &'static str = \"{}\";\n\n",
        naming::escape_str(op_id)
    ));

    render_into_http_request(out, op);
    out.push('\n');
    render_parse_response(out, spec, op, output_name, error_name);
    out.push_str("}\n");
}

fn render_into_http_request(out: &mut String, op: &ir::Operation) {
    out.push_str("    fn into_http_request(self) -> Result<http::Request<Self::RequestBody>, Self::Error> {\n");
    out.push_str("        let Self {\n");
    let mut field_names = Vec::new();
    for p in op
        .path_params
        .iter()
        .chain(&op.query_params)
        .chain(&op.header_params)
    {
        field_names.push(naming::snake_case(&p.name));
    }
    if op.request_body.is_some() {
        field_names.push("body".to_string());
    }
    for f in &field_names {
        out.push_str(&format!("            {f},\n"));
    }
    out.push_str("        } = self;\n\n");

    // Path: rewrite `/api/org/{tenant}/...` with snake-case keys so
    // `format!` matches our destructured locals.
    let path_template = rewrite_path_for_format(&op.path_template, &op.path_params);
    if op.path_params.is_empty() {
        out.push_str(&format!(
            "        let path = String::from(\"{}\");\n",
            naming::escape_str(&path_template)
        ));
    } else {
        let args: Vec<String> = op
            .path_params
            .iter()
            .map(|p| {
                let snake = naming::snake_case(&p.name);
                format!("{snake} = {snake}")
            })
            .collect();
        out.push_str(&format!(
            "        let path = format!(\"{}\", {});\n",
            naming::escape_str(&path_template),
            args.join(", ")
        ));
    }

    out.push_str("        let mut builder = http::Request::builder()\n");
    out.push_str("            .method(Self::METHOD)\n");
    out.push_str("            .uri(path.as_str());\n");

    // Query string.
    if !op.query_params.is_empty() {
        out.push_str("        let mut query = String::new();\n");
        for p in &op.query_params {
            let snake = naming::snake_case(&p.name);
            let key = naming::escape_str(&p.name);
            if p.required {
                out.push_str(&format!(
                    "        runtime::push_query(&mut query, \"{key}\", &{snake}.to_string());\n"
                ));
            } else {
                out.push_str(&format!(
                    "        if let Some(v) = &{snake} {{ runtime::push_query(&mut query, \"{key}\", &v.to_string()); }}\n"
                ));
            }
        }
        out.push_str("        let final_uri = if query.is_empty() { path } else { format!(\"{path}?{query}\") };\n");
        out.push_str("        builder = builder.uri(final_uri.as_str());\n");
    }

    // Headers.
    for p in &op.header_params {
        let snake = naming::snake_case(&p.name);
        let key = naming::escape_str(&p.name);
        if p.required {
            out.push_str(&format!(
                "        builder = builder.header(\"{key}\", {snake}.to_string());\n"
            ));
        } else {
            out.push_str(&format!(
                "        if let Some(v) = {snake}.as_ref() {{ builder = builder.header(\"{key}\", v.to_string()); }}\n"
            ));
        }
    }

    // Body.
    match &op.request_body {
        Some(body) => {
            if body
                .content
                .iter()
                .any(|c| c.media_type == "application/json")
            {
                out.push_str(
                    "        builder = builder.header(http::header::CONTENT_TYPE, \"application/json\");\n",
                );
                if body.required {
                    out.push_str(
                        "        let bytes = serde_json::to_vec(&body).map_err(Self::Error::Decode)?;\n",
                    );
                    out.push_str(
                        "        let request_body = http_body_util::Full::new(bytes::Bytes::from(bytes));\n",
                    );
                } else {
                    out.push_str(
                        "        let bytes = match body { Some(b) => serde_json::to_vec(&b).map_err(Self::Error::Decode)?, None => Vec::new() };\n",
                    );
                    out.push_str(
                        "        let request_body = http_body_util::Full::new(bytes::Bytes::from(bytes));\n",
                    );
                }
            } else {
                out.push_str("        // TODO non-JSON body — encode as bytes here.\n");
                out.push_str(
                    "        let request_body = http_body_util::Full::new(bytes::Bytes::new());\n",
                );
            }
        }
        None => out.push_str(
            "        let request_body = http_body_util::Full::new(bytes::Bytes::new());\n",
        ),
    }

    out.push_str("        Ok(builder.body(request_body)?)\n");
    out.push_str("    }\n");

    // Inline helper at the impl body's top — emitted once per impl, fine.
    if !op.query_params.is_empty() {
        // We need a free function in scope for `push_query`. Re-emit it as
        // a closure-free fn at module scope by appending it after the impl.
        // (Actually emit it as a local fn inside `into_http_request` so it
        // doesn't pollute the module.) — adjust: easiest is a free fn at
        // module scope. We add it after the operation_impl block ends.
    }
}

/// Rewrite `/foo/{rawName}/bar` to `/foo/{rust_name}/bar` so it composes
/// with `format!(..., rust_name = rust_name)`.
fn rewrite_path_for_format(path: &str, path_params: &[ir::Parameter]) -> String {
    let mut out = String::with_capacity(path.len());
    let chars: Vec<char> = path.chars().collect();
    let mut i = 0;
    while i < chars.len() {
        let c = chars[i];
        if c == '{' {
            let end = chars[i..].iter().position(|&c| c == '}').map(|p| i + p);
            match end {
                Some(end) => {
                    let raw: String = chars[i + 1..end].iter().collect();
                    let mapped = path_params
                        .iter()
                        .find(|p| p.name == raw)
                        .map(|p| naming::snake_case(&p.name))
                        .unwrap_or_else(|| naming::snake_case(&raw));
                    out.push('{');
                    out.push_str(&mapped);
                    out.push('}');
                    i = end + 1;
                    continue;
                }
                None => {
                    out.push(c);
                    i += 1;
                    continue;
                }
            }
        }
        if c == '}' {
            out.push(c);
            i += 1;
            continue;
        }
        out.push(c);
        i += 1;
    }
    out
}

fn render_parse_response(
    out: &mut String,
    spec: &ir::Ir,
    op: &ir::Operation,
    output_name: &str,
    error_name: &str,
) {
    out.push_str("    async fn parse_response<B>(\n");
    out.push_str("        resp: http::Response<B>,\n");
    out.push_str(&format!("    ) -> Result<{output_name}, {error_name}>\n"));
    out.push_str("    where\n");
    out.push_str("        B: http_body::Body + Send + 'static,\n");
    out.push_str("        B::Data: Send,\n");
    out.push_str("        B::Error: Into<Box<dyn std::error::Error + Send + Sync>>,\n");
    out.push_str("    {\n");
    out.push_str("        let (parts, body) = resp.into_parts();\n");
    out.push_str(
        "        let bytes = runtime::collect_bytes(body).await.map_err(|e| Self::Error::Body(e.into()))?;\n",
    );
    out.push_str("        match parts.status.as_u16() {\n");
    let default_resp = op
        .responses
        .iter()
        .find(|r| matches!(r.status, ir::ResponseStatus::Default));
    for resp in &op.responses {
        if matches!(resp.status, ir::ResponseStatus::Default) {
            continue; // handled as the catch-all arm below
        }
        let status_codes = numeric_status_codes(&resp.status);
        let variant = status_variant(&resp.status);
        let body = pick_json_response_body(resp);
        for code in status_codes {
            match body {
                Some(_) => {
                    out.push_str(&format!(
                        "            {code} => Ok({output_name}::{variant}(serde_json::from_slice(&bytes)?)),\n"
                    ));
                }
                None => {
                    out.push_str(&format!(
                        "            {code} => Ok({output_name}::{variant}),\n"
                    ));
                }
            }
        }
    }
    if op.responses.is_empty() {
        out.push_str(&format!(
            "            s if (200..300).contains(&s) => Ok({output_name}::Success),\n"
        ));
    }
    // Catch-all: a `default` response (when declared) absorbs any status the
    // explicit arms didn't match. Otherwise we surface `UndeclaredStatus`.
    match default_resp {
        Some(resp) => {
            let variant = status_variant(&resp.status);
            match pick_json_response_body(resp) {
                Some(_) => out.push_str(&format!(
                    "            _ => Ok({output_name}::{variant}(serde_json::from_slice(&bytes)?)),\n"
                )),
                None => out.push_str(&format!(
                    "            _ => Ok({output_name}::{variant}),\n"
                )),
            }
        }
        None => {
            out.push_str("            status => Err(Self::Error::UndeclaredStatus {\n");
            out.push_str("                status,\n");
            out.push_str("                body: String::from_utf8_lossy(&bytes).into_owned(),\n");
            out.push_str("            }),\n");
        }
    }
    out.push_str("        }\n");
    out.push_str("    }\n");
    let _ = spec;
}

fn pick_json_response_body(resp: &ir::Response) -> Option<&str> {
    resp.content
        .iter()
        .find(|c| c.media_type == "application/json")
        .map(|c| c.r#type.as_str())
}

/// Variant name on the per-op response enum for a given status. We name
/// after the canonical HTTP reason phrase where one exists; default and
/// `1xx/2xx/...` ranges fall back to descriptive names.
fn status_variant(s: &ir::ResponseStatus) -> String {
    match s {
        ir::ResponseStatus::Explicit { code } => {
            well_known_variant(*code).unwrap_or_else(|| format!("Status{code}"))
        }
        ir::ResponseStatus::Range { class } => match class {
            1 => "OneXx".to_string(),
            2 => "TwoXx".to_string(),
            3 => "ThreeXx".to_string(),
            4 => "FourXx".to_string(),
            5 => "FiveXx".to_string(),
            other => format!("Status{other}xx"),
        },
        ir::ResponseStatus::Default => "Default".to_string(),
    }
}

/// Numeric status codes (or Rust range patterns) to match on for a given
/// `ResponseStatus`. Exact codes produce `"200"`; ranges produce
/// `"200..=299"`; `Default` is handled by the catch-all arm and returns no
/// pattern of its own.
fn numeric_status_codes(s: &ir::ResponseStatus) -> Vec<String> {
    match s {
        ir::ResponseStatus::Explicit { code } => vec![code.to_string()],
        ir::ResponseStatus::Range { class } => match class {
            1 => vec!["100..=199".to_string()],
            2 => vec!["200..=299".to_string()],
            3 => vec!["300..=399".to_string()],
            4 => vec!["400..=499".to_string()],
            5 => vec!["500..=599".to_string()],
            _ => vec![],
        },
        ir::ResponseStatus::Default => vec![],
    }
}

fn well_known_variant(code: u16) -> Option<String> {
    let n = match code {
        100 => "Continue",
        101 => "SwitchingProtocols",
        200 => "Ok",
        201 => "Created",
        202 => "Accepted",
        203 => "NonAuthoritativeInformation",
        204 => "NoContent",
        205 => "ResetContent",
        206 => "PartialContent",
        300 => "MultipleChoices",
        301 => "MovedPermanently",
        302 => "Found",
        303 => "SeeOther",
        304 => "NotModified",
        307 => "TemporaryRedirect",
        308 => "PermanentRedirect",
        400 => "BadRequest",
        401 => "Unauthorized",
        402 => "PaymentRequired",
        403 => "Forbidden",
        404 => "NotFound",
        405 => "MethodNotAllowed",
        406 => "NotAcceptable",
        407 => "ProxyAuthenticationRequired",
        408 => "RequestTimeout",
        409 => "Conflict",
        410 => "Gone",
        411 => "LengthRequired",
        412 => "PreconditionFailed",
        413 => "PayloadTooLarge",
        414 => "RequestUriTooLong",
        415 => "UnsupportedMediaType",
        416 => "RangeNotSatisfiable",
        417 => "ExpectationFailed",
        422 => "UnprocessableEntity",
        425 => "TooEarly",
        426 => "UpgradeRequired",
        428 => "PreconditionRequired",
        429 => "TooManyRequests",
        431 => "RequestHeaderFieldsTooLarge",
        500 => "InternalServerError",
        501 => "NotImplemented",
        502 => "BadGateway",
        503 => "ServiceUnavailable",
        504 => "GatewayTimeout",
        505 => "HttpVersionNotSupported",
        _ => return None,
    };
    Some(n.to_string())
}
