//! Generation entry point. Emits a buildable Rust CLI crate (clap
//! derive + reqwest) with tag-grouped subcommands. When the spec
//! plus plugin config opt in, the emitted CLI also supports OAuth
//! 2.0 PKCE login/logout and optional RFC-8693 token exchange driven
//! by a generic `x-token-exchange` extension on the chosen `oauth2`
//! security scheme.

use std::collections::BTreeSet;

use forge_plugin_sdk::ir::{
    Body, HttpMethod, Ir, OAuth2Flow, OAuth2FlowKind, Operation, Parameter, SecurityScheme,
    SecuritySchemeKind,
};
use forge_plugin_sdk::{values_ext, GenerationOutput, OutputFile};
use proc_macro2::TokenStream;
use quote::{format_ident, quote};

use crate::config::{Config, OAuthConfig};
use crate::naming::{kebab_case, pascal_case, screaming_snake, snake_case};
use crate::schema;
use crate::tags::{self, TagGroup, TagTree};

const GEN_HEADER: &str =
    "// Generated by openapi-forge / generator-rust-clap; do not edit by hand.\n\n";

/// Token stream → formatted Rust source. Matches the helper
/// `generator-rust-tower::emit::render_file` uses: parse through
/// `syn::File` so we hard-fail on bad emissions, then prepend the
/// `// Generated by …` header in plain text (syn doesn't model line
/// comments).
fn render_file(tokens: TokenStream) -> String {
    let file: syn::File = syn::parse2(tokens).expect("generator produced invalid Rust");
    format!("{GEN_HEADER}{}", prettyplease::unparse(&file))
}

pub fn all(ir: &Ir, cfg: &Config) -> GenerationOutput {
    let bin_name = bin_name(ir, cfg);
    let pkg_name = format!("{bin_name}-cli");
    let oauth = detect_oauth(ir, cfg);

    let mut files = vec![
        OutputFile::text(
            "Cargo.toml",
            emit_cargo_toml(&pkg_name, &bin_name, oauth.is_some()),
        ),
        OutputFile::text(
            "src/main.rs",
            emit_main_rs(ir, cfg, &bin_name, oauth.as_ref()),
        ),
        OutputFile::text("src/client.rs", emit_client_rs(ir)),
        OutputFile::text("src/runtime.rs", emit_runtime_rs()),
        OutputFile::text("README.md", emit_readme(ir, &bin_name, oauth.as_ref())),
    ];
    if let Some(oa) = &oauth {
        files.push(OutputFile::text(
            "src/auth.rs",
            emit_auth_rs(&bin_name, oa, &default_base_url(ir, cfg)),
        ));
    }

    GenerationOutput {
        files,
        diagnostics: vec![],
    }
}

fn bin_name(ir: &Ir, cfg: &Config) -> String {
    if let Some(n) = cfg.name.as_deref().filter(|s| !s.is_empty()) {
        return kebab_case(n);
    }
    let title = ir.info.title.trim();
    if title.is_empty() {
        "api-cli".into()
    } else {
        kebab_case(title)
    }
}

fn default_base_url(ir: &Ir, cfg: &Config) -> String {
    if let Some(u) = cfg.base_url.as_deref().filter(|s| !s.is_empty()) {
        return u.to_string();
    }
    ir.servers
        .first()
        .map(|s| s.url.clone())
        .unwrap_or_else(|| "http://localhost".into())
}

fn env_prefix(bin_name: &str) -> String {
    screaming_snake(bin_name)
}

// ---------------------------------------------------------------------------
// OAuth activation + token-exchange detection
// ---------------------------------------------------------------------------

struct OauthInfo<'a> {
    flow: &'a OAuth2Flow,
    config: &'a OAuthConfig,
    scopes: Vec<String>,
    exchange: Option<TokenExchangeInfo>,
}

#[derive(Debug, Clone)]
struct TokenExchangeInfo {
    /// Audience template like `"urn:vendor:tenant:{tenant}"`.
    audience_template: String,
    /// Single placeholder name extracted from the template. v0.0.6
    /// supports exactly one placeholder; multi-placeholder is a
    /// followup.
    placeholder: String,
    /// Optional RFC 8707 `resource` template.
    resource_template: Option<String>,
    /// Optional extra scopes to request on the exchange.
    extra_scope: Vec<String>,
}

fn detect_oauth<'a>(ir: &'a Ir, cfg: &'a Config) -> Option<OauthInfo<'a>> {
    let oc = cfg.oauth.as_ref()?;
    if oc.client_id.is_empty() {
        return None;
    }
    let mut candidates: Vec<&SecurityScheme> = ir
        .security_schemes
        .iter()
        .filter(|s| matches!(s.kind, SecuritySchemeKind::Oauth2(_)))
        .collect();
    if let Some(want_id) = &oc.scheme_id {
        candidates.retain(|s| s.id == *want_id);
    }
    candidates.sort_by(|a, b| a.id.cmp(&b.id));

    for s in candidates {
        if let SecuritySchemeKind::Oauth2(scheme) = &s.kind {
            for f in &scheme.flows {
                let usable = matches!(f.kind, OAuth2FlowKind::AuthorizationCode)
                    && f.authorization_url.is_some()
                    && f.token_url.is_some();
                if !usable {
                    continue;
                }
                let scopes = if let Some(o) = &oc.scopes {
                    o.clone()
                } else {
                    let mut set: BTreeSet<String> = BTreeSet::new();
                    for op in &ir.operations {
                        for req in &op.security {
                            if req.scheme_id == s.id {
                                for sc in &req.scopes {
                                    set.insert(sc.clone());
                                }
                            }
                        }
                    }
                    set.into_iter().collect()
                };
                let exchange = parse_token_exchange(ir, s);
                return Some(OauthInfo {
                    flow: f,
                    config: oc,
                    scopes,
                    exchange,
                });
            }
        }
    }
    None
}

fn parse_token_exchange(ir: &Ir, scheme: &SecurityScheme) -> Option<TokenExchangeInfo> {
    let (_, vref) = scheme
        .extensions
        .iter()
        .find(|(k, _)| k == "x-token-exchange")?;
    let json = values_ext::resolve_to_serde(&ir.values, *vref);
    let obj = json.as_object()?;

    let audience_template = obj.get("audience-template")?.as_str()?.to_string();
    let placeholders = extract_placeholders(&audience_template);
    if placeholders.len() != 1 {
        // v0.0.6 supports exactly one placeholder. Multi-placeholder is a
        // followup. Falling back to non-exchange mode.
        return None;
    }
    let placeholder = placeholders.into_iter().next().unwrap();

    let resource_template = obj
        .get("resource-template")
        .and_then(|v| v.as_str())
        .map(|s| s.to_string());

    let extra_scope: Vec<String> = obj
        .get("scope")
        .and_then(|v| v.as_array())
        .map(|arr| {
            arr.iter()
                .filter_map(|v| v.as_str().map(|s| s.to_string()))
                .collect()
        })
        .unwrap_or_default();

    Some(TokenExchangeInfo {
        audience_template,
        placeholder,
        resource_template,
        extra_scope,
    })
}

fn extract_placeholders(template: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut chars = template.chars().peekable();
    while let Some(c) = chars.next() {
        if c == '{' {
            let mut name = String::new();
            for c2 in chars.by_ref() {
                if c2 == '}' {
                    break;
                }
                name.push(c2);
            }
            if !name.is_empty() && !out.contains(&name) {
                out.push(name);
            }
        }
    }
    out
}

fn op_uses_placeholder(op: &Operation, placeholder: &str) -> bool {
    op.path_params
        .iter()
        .any(|p| snake_case(&p.name) == snake_case(placeholder))
}

// ---------------------------------------------------------------------------
// Cargo.toml
// ---------------------------------------------------------------------------

fn emit_cargo_toml(pkg_name: &str, bin_name: &str, oauth: bool) -> String {
    let oauth_block = if oauth {
        r#"sha2 = "0.10"
base64 = "0.22"
rand = "0.8"
webbrowser = "1"
directories = "6"
toml = "0.8"
dialoguer = "0.11"
"#
    } else {
        ""
    };
    format!(
        r#"# Generated by openapi-forge / generator-rust-clap.
[package]
name = "{pkg_name}"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "{bin_name}"
path = "src/main.rs"

[dependencies]
clap = {{ version = "4", features = ["derive", "env"] }}
clap_complete = {{ version = "4", features = ["unstable-dynamic"] }}
tokio = {{ version = "1", features = ["macros", "rt-multi-thread", "net", "io-util", "sync"] }}
serde = {{ version = "1", features = ["derive"] }}
serde_json = "1"
anyhow = "1"
reqwest = {{ version = "0.12", default-features = false, features = ["json", "rustls-tls"] }}
urlencoding = "2"
{oauth_block}"#
    )
}

// ---------------------------------------------------------------------------
// src/main.rs
// ---------------------------------------------------------------------------

fn emit_main_rs(ir: &Ir, cfg: &Config, bin_name: &str, oauth: Option<&OauthInfo>) -> String {
    let title = ir.info.title.as_str();
    let version = ir.info.version.as_str();
    let base_url = default_base_url(ir, cfg);
    let prefix = env_prefix(bin_name);
    let prefix_base_url_env = format!("{prefix}_BASE_URL");
    let prefix_token_env = format!("{prefix}_TOKEN");
    let prefix_profile_env = format!("{prefix}_PROFILE");

    let tree = tags::build(ir);
    let oauth_active = oauth.is_some();
    let exchange = oauth.and_then(|o| o.exchange.as_ref());
    let placeholder_kebab = exchange.map(|e| kebab_case(&e.placeholder));
    let placeholder_snake = exchange.map(|e| snake_case(&e.placeholder));
    let placeholder_pascal_str = exchange.map(|e| pascal_case(&e.placeholder));
    let placeholder_pascal_ident = placeholder_pascal_str
        .as_deref()
        .map(|p| format_ident!("{}", p));

    let schema_consts = emit_schema_consts(ir);
    let long_about_lit = build_long_about(
        title,
        bin_name,
        &prefix,
        oauth_active,
        placeholder_kebab.as_deref(),
    );

    // CLI struct fields are emitted in document order. Each branch produces
    // a TokenStream that's spliced into the `#[derive(Parser)] struct Cli`.
    let base_url_field = if oauth_active {
        quote! {
            /// API base URL. When unset, falls back to the active profile, then the spec default.
            #[arg(long, global = true, env = #prefix_base_url_env)]
            base_url: Option<String>,
        }
    } else {
        quote! {
            /// API base URL.
            #[arg(long, global = true, env = #prefix_base_url_env, default_value = #base_url)]
            base_url: String,
        }
    };
    let profile_field = if oauth_active {
        quote! {
            /// Profile to use; bundles base_url / auth_url / token_url / client_id / client_secret. Default: "default".
            #[arg(long, global = true, env = #prefix_profile_env, default_value = "default", add = clap_complete::ArgValueCandidates::new(__complete_profile_names))]
            profile: String,
        }
    } else {
        quote!()
    };
    let placeholder_field = match (&placeholder_kebab, &placeholder_snake) {
        (Some(kebab), Some(snake)) => {
            let snake_ident = format_ident!("{}", snake);
            let env_name = format!("{}_{}", prefix, screaming_snake(snake));
            quote! {
                /// Slug used to template the RFC 8693 exchange audience for tenant-scoped operations.
                #[arg(long = #kebab, global = true, env = #env_name)]
                #snake_ident: Option<String>,
            }
        }
        _ => quote!(),
    };

    let complete_profile_fn = if oauth_active {
        quote! {
            /// Dynamic-completion callback for the global `--profile` flag.
            /// Invoked at completion time by the shell; reads `config.toml` fresh.
            fn __complete_profile_names() -> Vec<clap_complete::CompletionCandidate> {
                auth::list_profile_names()
                    .into_iter()
                    .map(clap_complete::CompletionCandidate::new)
                    .collect()
            }
        }
    } else {
        quote!()
    };

    // Cmd enum + per-group sub-enums.
    let cmd_enum = if ir.operations.is_empty() && !oauth_active {
        quote! {
            #[derive(Subcommand)]
            enum Cmd {
                /// (No operations declared in the spec.)
                #[command(hide = true)]
                Noop,
            }
        }
    } else {
        emit_root_enum(
            &tree,
            oauth_active,
            exchange,
            placeholder_pascal_ident.as_ref(),
            placeholder_kebab.as_deref(),
        )
    };
    let group_types: TokenStream = if ir.operations.is_empty() && !oauth_active {
        quote!()
    } else {
        tree.roots
            .iter()
            .map(|root| emit_group_types(root, "", exchange))
            .collect()
    };

    // main() body — assembled from a sequence of optional blocks.
    let completion_dispatch = if oauth_active {
        quote! {
            // Dynamic shell-completion dispatch. When `COMPLETE` env is set
            // (e.g. by `eval "$(COMPLETE=bash <bin>)"` in shell init), this
            // prints completions and exits before any normal CLI handling.
            clap_complete::CompleteEnv::with_factory(Cli::command).complete();
        }
    } else {
        quote!()
    };
    let completion_subcommand = quote! {
        if let Cmd::Completion { shell } = cli.cmd {
            let mut cmd = Cli::command();
            clap_complete::generate(shell, &mut cmd, #bin_name, &mut std::io::stdout());
            return Ok(());
        }
    };
    let bootstrap_block = if oauth_active {
        quote! {
            auth::migrate_legacy()?;
            auth::bootstrap_default_profile_if_missing()?;
        }
    } else {
        quote!()
    };
    let builtin_handlers = if oauth_active {
        quote! {
            if matches!(cli.cmd, Cmd::Login) {
                auth::login(&cli.profile).await?;
                eprintln!("logged in (profile: {})", cli.profile);
                return Ok(());
            }
            if matches!(cli.cmd, Cmd::Logout) {
                let removed = auth::logout(&cli.profile).await?;
                eprintln!("{}", if removed { "logged out" } else { "no stored token" });
                return Ok(());
            }
            if let Cmd::Configure {
                base_url,
                auth_url,
                token_url,
                client_id,
                client_secret,
                non_interactive,
            } = &cli.cmd
            {
                let any_field = base_url.is_some()
                    || auth_url.is_some()
                    || token_url.is_some()
                    || client_id.is_some()
                    || client_secret.is_some();
                if *non_interactive || any_field {
                    auth::write_profile_fields(
                        &cli.profile,
                        base_url.clone(),
                        auth_url.clone(),
                        token_url.clone(),
                        client_id.clone(),
                        client_secret.clone(),
                    )?;
                } else {
                    let should_login = auth::interactive_configure(&cli.profile)?;
                    if should_login {
                        auth::login(&cli.profile).await?;
                        eprintln!("logged in (profile: {})", cli.profile);
                    }
                }
                return Ok(());
            }
            if let Cmd::Profile(args) = &cli.cmd {
                match &args.cmd {
                    ProfileCmd::List => {
                        for name in auth::list_profile_names() {
                            println!("{}", name);
                        }
                        return Ok(());
                    }
                    ProfileCmd::Show { name } => {
                        let p = name.as_deref().unwrap_or(cli.profile.as_str());
                        auth::show_profile(p)?;
                        return Ok(());
                    }
                    ProfileCmd::Remove { name } => {
                        let removed = auth::remove_profile(name)?;
                        eprintln!("{}", if removed { "removed" } else { "not found" });
                        return Ok(());
                    }
                }
            }
        }
    } else {
        quote!()
    };
    let placeholder_handlers = match (
        placeholder_pascal_ident.as_ref(),
        placeholder_kebab.as_deref(),
    ) {
        (Some(pascal), Some(kebab)) => {
            let set_v = format_ident!("Set{}", pascal);
            let unset_v = format_ident!("Unset{}", pascal);
            let show_v = format_ident!("Show{}", pascal);
            let persist_msg = format!("persisted {kebab} = {{}} (profile: {{}})");
            quote! {
                if let Cmd::#set_v { value } = &cli.cmd {
                    auth::write_persisted(&cli.profile, #kebab, value)?;
                    eprintln!(#persist_msg, value, cli.profile);
                    return Ok(());
                }
                if matches!(cli.cmd, Cmd::#unset_v) {
                    let removed = auth::delete_persisted(&cli.profile, #kebab)?;
                    eprintln!("{}", if removed { "unset" } else { "no persisted value" });
                    return Ok(());
                }
                if matches!(cli.cmd, Cmd::#show_v) {
                    match auth::read_persisted(&cli.profile, #kebab)? {
                        Some(v) => println!("{}", v),
                        None => eprintln!("(none)"),
                    }
                    return Ok(());
                }
            }
        }
        _ => quote!(),
    };
    let placeholder_resolve = match (placeholder_snake.as_deref(), placeholder_kebab.as_deref()) {
        (Some(snake), Some(kebab)) => {
            let resolved_ident = format_ident!("__resolved_{}", snake);
            let cli_field = format_ident!("{}", snake);
            quote! {
                let #resolved_ident: Option<String> = match cli.#cli_field.clone() {
                    Some(v) => Some(v),
                    None => auth::read_persisted(&cli.profile, #kebab)?,
                };
            }
        }
        _ => quote!(),
    };
    let client_init = if oauth_active {
        quote! {
            let __base_url = auth::resolve_base_url(&cli.profile, cli.base_url.as_deref())?;
            let client = ApiClient::new(__base_url)?;
        }
    } else {
        quote! { let client = ApiClient::new(cli.base_url)?; }
    };

    let mut match_arms: Vec<TokenStream> =
        vec![quote!(Cmd::Completion { .. } => unreachable!("handled above"),)];
    if oauth_active {
        match_arms.push(
            quote!(Cmd::Login | Cmd::Logout | Cmd::Configure { .. } | Cmd::Profile(_) => unreachable!("handled above"),),
        );
    }
    if let Some(pascal) = placeholder_pascal_ident.as_ref() {
        let set_v = format_ident!("Set{}", pascal);
        let unset_v = format_ident!("Unset{}", pascal);
        let show_v = format_ident!("Show{}", pascal);
        match_arms.push(
            quote!(Cmd::#set_v { .. } | Cmd::#unset_v | Cmd::#show_v => unreachable!("handled above"),),
        );
    }
    if ir.operations.is_empty() && !oauth_active {
        match_arms.push(quote!(Cmd::Noop => return Ok(()),));
    } else {
        for root in &tree.roots {
            match_arms.push(emit_root_match_arms(root, "", oauth, exchange));
        }
    }

    let tokio_main = quote! {
        #[tokio::main(flavor = "multi_thread")]
        async fn main() -> anyhow::Result<()> {
            #completion_dispatch
            let cli = Cli::parse();
            #completion_subcommand
            #bootstrap_block
            #builtin_handlers
            #placeholder_handlers
            #placeholder_resolve
            #client_init
            let result: serde_json::Value = match cli.cmd {
                #(#match_arms)*
            };
            runtime::print_output(&result, cli.output)
        }
    };

    let mod_decls = if oauth_active {
        quote! {
            mod auth;
            mod client;
            mod runtime;
        }
    } else {
        quote! {
            mod client;
            mod runtime;
        }
    };

    render_file(quote! {
        #![allow(
            clippy::needless_late_init,
            clippy::redundant_field_names,
            clippy::too_many_arguments,
            clippy::collapsible_if
        )]

        #mod_decls

        use clap::{Args, CommandFactory, Parser, Subcommand};
        use client::ApiClient;
        use runtime::OutputMode;

        #schema_consts

        #[derive(Parser)]
        #[command(
            name = #bin_name,
            version = #version,
            about = #title,
            long_about = #long_about_lit,
        )]
        struct Cli {
            #base_url_field
            /// Bearer token. Overrides any stored OAuth or exchanged token.
            #[arg(long, global = true, env = #prefix_token_env)]
            token: Option<String>,

            /// Output mode for response bodies.
            #[arg(long, global = true, value_enum, default_value_t = OutputMode::Json)]
            output: OutputMode,

            #profile_field
            #placeholder_field

            #[command(subcommand)]
            cmd: Cmd,
        }

        #complete_profile_fn

        #cmd_enum

        #group_types

        #tokio_main
    })
}

fn emit_root_enum(
    tree: &TagTree,
    oauth_active: bool,
    exchange: Option<&TokenExchangeInfo>,
    placeholder_pascal: Option<&proc_macro2::Ident>,
    placeholder_kebab: Option<&str>,
) -> TokenStream {
    let oauth_variants = if oauth_active {
        quote! {
            /// Run OAuth 2.0 authorization-code flow with PKCE; persists the access token.
            Login,
            /// Delete the stored OAuth token.
            Logout,
            /// Create or edit the active profile (use `--profile` to pick). With no flags, prompts interactively; with `--non-interactive` (or any field flag), writes without prompting.
            Configure {
                /// Set base_url non-interactively.
                #[arg(long)]
                base_url: Option<String>,
                /// Set auth_url non-interactively.
                #[arg(long)]
                auth_url: Option<String>,
                /// Set token_url non-interactively.
                #[arg(long)]
                token_url: Option<String>,
                /// Set client_id non-interactively.
                #[arg(long)]
                client_id: Option<String>,
                /// Set client_secret non-interactively. Stored in `config.toml` (mode 0600). Prefer setting via the env var when possible.
                #[arg(long)]
                client_secret: Option<String>,
                /// Skip all prompts. Fields not given as flags keep their existing value.
                #[arg(long)]
                non_interactive: bool,
            },
            /// List, inspect, or delete profiles.
            Profile(ProfileArgs),
        }
    } else {
        quote!()
    };
    let exchange_variants = match (exchange, placeholder_pascal, placeholder_kebab) {
        (Some(_), Some(pascal), Some(kebab)) => {
            let set_v = format_ident!("Set{}", pascal);
            let unset_v = format_ident!("Unset{}", pascal);
            let show_v = format_ident!("Show{}", pascal);
            let set_doc =
                format!("Persist a default `{kebab}` so subsequent calls can omit `--{kebab}`.");
            let unset_doc = format!("Clear the persisted default `{kebab}`.");
            let show_doc = format!("Print the persisted default `{kebab}`.");
            quote! {
                #[doc = #set_doc]
                #set_v { value: String },
                #[doc = #unset_doc]
                #unset_v,
                #[doc = #show_doc]
                #show_v,
            }
        }
        _ => quote!(),
    };
    let root_variants: Vec<TokenStream> = tree
        .roots
        .iter()
        .flat_map(|root| {
            if root.is_misc() {
                root.direct_ops
                    .iter()
                    .map(|op| render_op_variant(op, exchange))
                    .collect::<Vec<_>>()
            } else {
                let variant = format_ident!("{}", pascal_case(&root.name));
                let qualified = format_ident!("{}Args", qualified_pascal("", &root.name));
                let doc_attr = group_doc(root).map(|d| quote!(#[doc = #d]));
                vec![quote!(#doc_attr #variant(#qualified),)]
            }
        })
        .collect();

    let profile_types = if oauth_active {
        quote! {
            #[derive(Args)]
            pub struct ProfileArgs {
                #[command(subcommand)]
                cmd: ProfileCmd,
            }

            #[derive(Subcommand)]
            pub enum ProfileCmd {
                /// List configured profile names from config.toml.
                List,
                /// Print the resolved settings for a profile (secret redacted).
                Show {
                    /// Profile name; defaults to the global --profile value.
                    #[arg(add = clap_complete::ArgValueCandidates::new(__complete_profile_names))]
                    name: Option<String>,
                },
                /// Delete a profile from config.toml and remove its on-disk dir.
                Remove {
                    /// Profile name (required to avoid accidental deletion).
                    #[arg(add = clap_complete::ArgValueCandidates::new(__complete_profile_names))]
                    name: String,
                },
            }
        }
    } else {
        quote!()
    };

    quote! {
        #[derive(Subcommand)]
        enum Cmd {
            /// Print a shell completion script. e.g. `source <(<bin> completion bash)`.
            Completion {
                /// Target shell.
                #[arg(value_enum)]
                shell: clap_complete::Shell,
            },
            #oauth_variants
            #exchange_variants
            #(#root_variants)*
        }

        #profile_types
    }
}

fn emit_group_types(
    group: &TagGroup,
    prefix: &str,
    exchange: Option<&TokenExchangeInfo>,
) -> TokenStream {
    if group.is_misc() {
        return quote!();
    }
    let q = qualified_pascal(prefix, &group.name);
    let args_ident = format_ident!("{}Args", q);
    let cmd_ident = format_ident!("{}Cmd", q);
    let about = group_doc(group).unwrap_or_default();

    let cmd_variants: Vec<TokenStream> = group
        .children
        .iter()
        .map(|child| {
            let child_q = qualified_pascal(&q, &child.name);
            let child_args = format_ident!("{}Args", child_q);
            let variant = format_ident!("{}", pascal_case(&child.name));
            let doc_attr = group_doc(child).map(|d| quote!(#[doc = #d]));
            quote!(#doc_attr #variant(#child_args),)
        })
        .chain(
            group
                .direct_ops
                .iter()
                .map(|op| render_op_variant(op, exchange)),
        )
        .collect();

    let child_types: TokenStream = group
        .children
        .iter()
        .map(|child| emit_group_types(child, &q, exchange))
        .collect();

    quote! {
        #[derive(Args)]
        #[command(about = #about)]
        pub struct #args_ident {
            #[command(subcommand)]
            cmd: #cmd_ident,
        }

        #[derive(Subcommand)]
        pub enum #cmd_ident {
            #(#cmd_variants)*
        }

        #child_types
    }
}

fn emit_root_match_arms(
    root: &TagGroup,
    prefix: &str,
    oauth: Option<&OauthInfo>,
    exchange: Option<&TokenExchangeInfo>,
) -> TokenStream {
    if root.is_misc() {
        let arms = root
            .direct_ops
            .iter()
            .map(|op| render_op_match_arm(op, &format_ident!("Cmd"), oauth, exchange));
        return quote!(#(#arms)*);
    }
    let variant = format_ident!("{}", pascal_case(&root.name));
    let q = qualified_pascal(prefix, &root.name);
    let inner = emit_group_match_arms(root, &q, oauth, exchange);
    quote! {
        Cmd::#variant(__g) => match __g.cmd {
            #inner
        },
    }
}

fn emit_group_match_arms(
    group: &TagGroup,
    q: &str,
    oauth: Option<&OauthInfo>,
    exchange: Option<&TokenExchangeInfo>,
) -> TokenStream {
    let cmd_ty = format_ident!("{}Cmd", q);
    let child_arms: Vec<TokenStream> = group
        .children
        .iter()
        .map(|child| {
            let child_variant = format_ident!("{}", pascal_case(&child.name));
            let child_q = qualified_pascal(q, &child.name);
            let inner = emit_group_match_arms(child, &child_q, oauth, exchange);
            quote! {
                #cmd_ty::#child_variant(__g) => match __g.cmd {
                    #inner
                },
            }
        })
        .collect();
    let op_arms: Vec<TokenStream> = group
        .direct_ops
        .iter()
        .map(|op| render_op_match_arm(op, &cmd_ty, oauth, exchange))
        .collect();
    quote! {
        #(#child_arms)*
        #(#op_arms)*
    }
}

fn render_op_variant(op: &Operation, exchange: Option<&TokenExchangeInfo>) -> TokenStream {
    let variant = format_ident!("{}", pascal_case(&op.id));
    let doc_attr = first_line(op.documentation.as_deref()).map(|d| quote!(#[doc = #d]));
    let exclude = exchange
        .filter(|ex| op_uses_placeholder(op, &ex.placeholder))
        .map(|ex| ex.placeholder.as_str());
    let fields = collect_fields(op, exclude);
    if fields.is_empty() {
        quote!(#doc_attr #variant,)
    } else {
        let tokens = fields.iter().map(field_to_tokens);
        quote!(#doc_attr #variant { #(#tokens)* },)
    }
}

fn render_op_match_arm(
    op: &Operation,
    cmd_ty: &proc_macro2::Ident,
    oauth: Option<&OauthInfo>,
    exchange: Option<&TokenExchangeInfo>,
) -> TokenStream {
    let variant = format_ident!("{}", pascal_case(&op.id));
    let method_ident = format_ident!("{}", snake_case(&op.id));

    // Bearer resolution per op. Three modes:
    //   - this op references the placeholder ⇒ resolve via RFC 8693
    //     exchange (or pass `--token` through unchanged).
    //   - oauth is active but op doesn't reference the placeholder ⇒
    //     fall back to the main token (`--token` ⇒ stored ⇒ none).
    //   - oauth not active ⇒ raw `--token` flag, possibly None.
    let needs_exchange = exchange.is_some_and(|ex| op_uses_placeholder(op, &ex.placeholder));
    let exclude = if needs_exchange {
        exchange.map(|ex| ex.placeholder.as_str())
    } else {
        None
    };
    let exclude_snake = exclude.map(snake_case);

    let destruct_fields = collect_fields(op, exclude);
    let destruct = if destruct_fields.is_empty() {
        quote!()
    } else {
        let idents = destruct_fields.iter().map(|f| &f.ident);
        quote!({ #(#idents),* })
    };

    // Schema-flag relaxation: when in effect, formerly-`String` fields
    // are emitted as `Option<String>` and clap allows them empty when
    // --body-schema / --response-schema is set; we unwrap with
    // `.expect(...)` on the actual API-call branch since clap
    // guarantees Some by then.
    let relax_active = !relax_unless(op).is_empty();
    let mut call_args: Vec<TokenStream> = vec![quote!(__bearer.as_deref())];
    for p in &op.path_params {
        let ident = format_ident!("{}", snake_case(&p.name));
        if exclude_snake
            .as_deref()
            .is_some_and(|s| s == snake_case(&p.name))
        {
            call_args.push(quote!(__slug.clone()));
        } else if relax_active {
            let msg = format!("<{}> required", kebab_case(&p.name));
            call_args.push(quote!(#ident.expect(#msg)));
        } else {
            call_args.push(quote!(#ident));
        }
    }
    let push_flag_args = |args: &mut Vec<TokenStream>, params: &[Parameter]| {
        for p in params {
            let ident = format_ident!("{}", snake_case(&p.name));
            if p.required && relax_active {
                let msg = format!("--{} required", kebab_case(&p.name));
                args.push(quote!(#ident.expect(#msg)));
            } else {
                args.push(quote!(#ident));
            }
        }
    };
    push_flag_args(&mut call_args, &op.query_params);
    push_flag_args(&mut call_args, &op.header_params);
    push_flag_args(&mut call_args, &op.cookie_params);
    if let Some(b) = &op.request_body {
        if b.required {
            // clap's `required_unless_present_any` guarantees `body` is
            // `Some` whenever we reach the API call branch.
            call_args.push(quote!(body.expect("--body required")));
        } else {
            call_args.push(quote!(body));
        }
    }
    let call = quote!(client.#method_ident(#(#call_args),*).await?);

    let (pre_let, bearer_let) = if needs_exchange {
        let ex = exchange.unwrap();
        let ph_snake = format_ident!("__resolved_{}", snake_case(&ex.placeholder));
        let ph_kebab = kebab_case(&ex.placeholder);
        let err_msg = format!(
            "--{0} is required for this operation (or run `set-{0} <slug>`)",
            ph_kebab,
        );
        let aud_fmt = ex
            .audience_template
            .replace(&format!("{{{}}}", ex.placeholder), "{}");
        let res_expr: TokenStream = match &ex.resource_template {
            Some(rt) => {
                let rt_fmt = rt.replace(&format!("{{{}}}", ex.placeholder), "{}");
                quote!(Some(format!(#rt_fmt, __slug)))
            }
            None => quote!(None),
        };
        let scope_expr: TokenStream = if ex.extra_scope.is_empty() {
            quote!(None)
        } else {
            let scopes = ex.extra_scope.join(" ");
            quote!(Some(#scopes))
        };
        (
            quote! {
                let __slug: String = #ph_snake
                    .clone()
                    .ok_or_else(|| anyhow::anyhow!(#err_msg))?;
            },
            quote! {
                let __bearer: Option<String> = if let Some(t) = cli.token.clone() {
                    Some(t)
                } else {
                    let __aud = format!(#aud_fmt, __slug);
                    let __res: Option<String> = #res_expr;
                    let __scope: Option<&str> = #scope_expr;
                    auth::audience_access_token(&cli.profile, &__aud, __res.as_deref(), __scope).await?
                };
            },
        )
    } else if oauth.is_some() {
        (
            quote!(),
            quote! {
                let __bearer: Option<String> = if let Some(t) = cli.token.clone() {
                    Some(t)
                } else {
                    auth::access_token(&cli.profile).await?
                };
            },
        )
    } else {
        (
            quote!(),
            quote!(let __bearer: Option<String> = cli.token.clone();),
        )
    };

    let const_pascal = screaming_snake(&op.id);
    let body_schema_const = format_ident!("BODY_SCHEMA_{}", const_pascal);
    let response_schema_const = format_ident!("RESPONSE_SCHEMA_{}", const_pascal);

    let has_body = op.request_body.is_some();
    let has_resp_schema = op_has_response_content(op);
    let api_call = quote! {
        #pre_let
        #bearer_let
        #call
    };
    let arm_body = match (has_body, has_resp_schema) {
        (false, false) => api_call,
        (true, false) => quote! {
            if body_schema {
                println!("{}", #body_schema_const);
                serde_json::Value::Null
            } else {
                #api_call
            }
        },
        (false, true) => quote! {
            if response_schema {
                println!("{}", #response_schema_const);
                serde_json::Value::Null
            } else {
                #api_call
            }
        },
        (true, true) => quote! {
            if body_schema {
                println!("{}", #body_schema_const);
                serde_json::Value::Null
            } else if response_schema {
                println!("{}", #response_schema_const);
                serde_json::Value::Null
            } else {
                #api_call
            }
        },
    };

    quote! {
        #cmd_ty::#variant #destruct => {
            #arm_body
        },
    }
}

struct Field {
    ident: proc_macro2::Ident,
    ty: TokenStream,
    doc: Option<String>,
    arg_attr: Option<TokenStream>,
}

fn field_to_tokens(f: &Field) -> TokenStream {
    let ident = &f.ident;
    let ty = &f.ty;
    let doc_attr = f.doc.as_ref().map(|d| quote!(#[doc = #d]));
    let arg_attr = f.arg_attr.as_ref().map(|a| quote!(#[arg(#a)]));
    quote!(#doc_attr #arg_attr #ident: #ty,)
}

fn collect_fields(op: &Operation, exclude_path_param: Option<&str>) -> Vec<Field> {
    let mut out = Vec::new();
    let exclude_snake = exclude_path_param.map(snake_case);
    let relax = relax_unless(op);
    for p in &op.path_params {
        if exclude_snake
            .as_deref()
            .is_some_and(|ex| ex == snake_case(&p.name))
        {
            continue;
        }
        out.push(field_for_param(p, FieldKind::Positional, &relax));
    }
    for p in &op.query_params {
        out.push(field_for_param(p, FieldKind::Flag, &relax));
    }
    for p in &op.header_params {
        out.push(field_for_param(p, FieldKind::Flag, &relax));
    }
    for p in &op.cookie_params {
        out.push(field_for_param(p, FieldKind::Flag, &relax));
    }
    if let Some(body) = &op.request_body {
        out.push(field_for_body(body, &relax));
        out.push(field_for_body_schema());
    }
    if op_has_response_content(op) {
        out.push(field_for_response_schema());
    }
    out
}

/// Schema-flag fields that suppress clap's required-arg gate on this
/// op's other params. Empty when the op has neither `--body-schema`
/// nor `--response-schema`.
fn relax_unless(op: &Operation) -> Vec<&'static str> {
    let mut v = Vec::new();
    if op.request_body.is_some() {
        v.push("body_schema");
    }
    if op_has_response_content(op) {
        v.push("response_schema");
    }
    v
}

#[derive(Copy, Clone)]
enum FieldKind {
    Positional,
    Flag,
}

fn field_for_param(p: &Parameter, kind: FieldKind, relax: &[&str]) -> Field {
    let ident = format_ident!("{}", snake_case(&p.name));
    let kebab = kebab_case(&p.name);
    let relax_active = !relax.is_empty();
    let relax_lits: Vec<&&str> = relax.iter().collect();

    let (ty, arg_attr) = match (kind, p.required) {
        (FieldKind::Positional, _) => {
            if relax_active {
                (
                    quote!(Option<String>),
                    Some(quote!(required_unless_present_any = [#(#relax_lits),*])),
                )
            } else {
                (quote!(String), None)
            }
        }
        (FieldKind::Flag, true) => {
            if relax_active {
                (
                    quote!(Option<String>),
                    Some(quote!(long = #kebab, required_unless_present_any = [#(#relax_lits),*])),
                )
            } else {
                (quote!(String), Some(quote!(long = #kebab)))
            }
        }
        (FieldKind::Flag, false) => (quote!(Option<String>), Some(quote!(long = #kebab))),
    };
    Field {
        ident,
        ty,
        doc: first_line(p.documentation.as_deref()),
        arg_attr,
    }
}

fn field_for_body(body: &Body, relax: &[&str]) -> Field {
    let relax_lits: Vec<&&str> = relax.iter().collect();
    let arg_attr = if body.required {
        quote!(long = "body", required_unless_present_any = [#(#relax_lits),*])
    } else {
        quote!(long = "body")
    };
    Field {
        ident: format_ident!("body"),
        ty: quote!(Option<String>),
        doc: Some(
            "Request body. Inline JSON, @file.json (read from file), or - (read from stdin). \
             Run with --body-schema to print the JSON Schema."
                .into(),
        ),
        arg_attr: Some(arg_attr),
    }
}

fn field_for_body_schema() -> Field {
    Field {
        ident: format_ident!("body_schema"),
        ty: quote!(bool),
        doc: Some("Print the JSON Schema for the request body and exit.".into()),
        arg_attr: Some(quote!(long = "body-schema")),
    }
}

fn field_for_response_schema() -> Field {
    Field {
        ident: format_ident!("response_schema"),
        ty: quote!(bool),
        doc: Some(
            "Print the JSON Schemas for the response bodies, keyed by status code, and exit."
                .into(),
        ),
        arg_attr: Some(quote!(long = "response-schema")),
    }
}

fn op_has_response_content(op: &Operation) -> bool {
    op.responses.iter().any(|r| !r.content.is_empty())
}

fn build_long_about(
    title: &str,
    bin_name: &str,
    prefix: &str,
    oauth_active: bool,
    exchange_placeholder_kebab: Option<&str>,
) -> String {
    let mut s = String::new();
    if !title.trim().is_empty() {
        s.push_str(title.trim());
        s.push_str("\n\n");
    }
    s.push_str(&format!(
        "Generated from an OpenAPI specification — each subcommand maps to one operation. \
         Run `{bin_name} help <command>` (or `<command> --help`) for per-operation flags.\n\n"
    ));

    s.push_str("Discover request and response shapes (no network call):\n");
    s.push_str(&format!(
        "  {bin_name} <op> --body-schema       JSON Schema for the request body.\n"
    ));
    s.push_str(&format!(
        "  {bin_name} <op> --response-schema   JSON Schemas for response bodies, keyed by status code.\n"
    ));
    s.push_str(
        "Bodies accept inline JSON, @file.json (read from file), or `-` (read from stdin).\n\n",
    );

    if oauth_active {
        s.push_str("Authentication and profiles:\n");
        s.push_str(&format!(
            "  {bin_name} login | logout         OAuth 2.0 authorization-code (PKCE); persists the access token.\n"
        ));
        s.push_str(&format!(
            "  {bin_name} configure              Edit the active profile (base_url, auth_url, client_id, ...).\n"
        ));
        s.push_str(&format!(
            "  {bin_name} profile <subcmd>       list | show | remove configured profiles.\n"
        ));
        s.push_str(
            "  --profile <name>                  Switch between configured profiles (default: \"default\").\n",
        );
        s.push_str(
            "  --token <jwt>                     Override the stored token for one call.\n\n",
        );
    }

    if let Some(ph) = exchange_placeholder_kebab {
        s.push_str("Multi-tenant operations:\n");
        s.push_str(&format!(
            "  Operations whose path includes `{{{ph}}}` mint a tenant-audienced JWT via RFC 8693 token exchange.\n"
        ));
        s.push_str(&format!(
            "  Pass `--{ph} <slug>` per call, or run `{bin_name} set-{ph} <slug>` to persist a default.\n\n"
        ));
    }

    s.push_str(&format!(
        "Shell completions: `{bin_name} completion <shell>` (bash | zsh | fish | powershell | elvish).\n"
    ));
    s.push_str(&format!(
        "Environment overrides: `{prefix}_BASE_URL`, `{prefix}_TOKEN`"
    ));
    if oauth_active {
        s.push_str(&format!(", `{prefix}_PROFILE`"));
    }
    s.push_str(", and per-flag env vars listed in each subcommand's help.");

    s
}

fn emit_schema_consts(ir: &Ir) -> TokenStream {
    let items = ir.operations.iter().flat_map(|op| {
        let pascal = screaming_snake(&op.id);
        let mut out: Vec<TokenStream> = Vec::new();
        if let Some(body) = &op.request_body {
            if let Some(s) = schema::render_body_schema(&ir.types, &ir.values, body) {
                let name = format_ident!("BODY_SCHEMA_{}", pascal);
                out.push(quote!(const #name: &str = #s;));
            }
        }
        if op_has_response_content(op) {
            if let Some(s) = schema::render_response_schemas(&ir.types, &ir.values, &op.responses) {
                let name = format_ident!("RESPONSE_SCHEMA_{}", pascal);
                out.push(quote!(const #name: &str = #s;));
            }
        }
        out
    });
    quote!(#(#items)*)
}
fn group_doc(group: &TagGroup) -> Option<String> {
    let tag = group.tag?;
    if let Some(s) = &tag.summary {
        if !s.is_empty() {
            return Some(s.clone());
        }
    }
    first_line(tag.description.as_deref())
}

fn qualified_pascal(prefix: &str, name: &str) -> String {
    format!("{prefix}{}", pascal_case(name))
}

// ---------------------------------------------------------------------------
// src/client.rs
// ---------------------------------------------------------------------------

fn emit_client_rs(ir: &Ir) -> String {
    let methods = ir.operations.iter().map(render_client_method);
    render_file(quote! {
        #![allow(clippy::too_many_arguments, clippy::needless_borrow)]

        use anyhow::{anyhow, Context, Result};
        use serde_json::Value;

        use crate::runtime::parse_body_arg;

        pub struct ApiClient {
            http: reqwest::Client,
            base_url: String,
        }

        impl ApiClient {
            pub fn new(base_url: String) -> Result<Self> {
                Ok(Self {
                    http: reqwest::Client::builder().build()?,
                    base_url: base_url.trim_end_matches('/').to_string(),
                })
            }

            fn req(
                &self,
                token: Option<&str>,
                method: reqwest::Method,
                path: &str,
            ) -> reqwest::RequestBuilder {
                let mut b = self
                    .http
                    .request(method, format!("{}{}", self.base_url, path));
                if let Some(t) = token {
                    b = b.bearer_auth(t);
                }
                b
            }

            #(#methods)*
        }
    })
}

fn render_client_method(op: &Operation) -> TokenStream {
    let method_ident = format_ident!("{}", snake_case(&op.id));
    let http_method = method_token(&op.method);

    // Function signature: __bearer first, then path/query/header/cookie
    // params, then optional body. `path_params` are always required
    // String; for the rest, required → String, optional → Option<String>.
    let mut sig_args: Vec<TokenStream> = vec![quote!(__bearer: Option<&str>)];
    for p in &op.path_params {
        let ident = format_ident!("{}", snake_case(&p.name));
        sig_args.push(quote!(#ident: String));
    }
    let push_optionable = |args: &mut Vec<TokenStream>, params: &[Parameter]| {
        for p in params {
            let ident = format_ident!("{}", snake_case(&p.name));
            if p.required {
                args.push(quote!(#ident: String));
            } else {
                args.push(quote!(#ident: Option<String>));
            }
        }
    };
    push_optionable(&mut sig_args, &op.query_params);
    push_optionable(&mut sig_args, &op.header_params);
    push_optionable(&mut sig_args, &op.cookie_params);
    if let Some(body) = &op.request_body {
        if body.required {
            sig_args.push(quote!(body: String));
        } else {
            sig_args.push(quote!(body: Option<String>));
        }
    }

    let (path_fmt, path_args) = render_path_interpolation(&op.path_template, &op.path_params);
    let path_decl = if path_args.is_empty() {
        quote!(let __path = String::from(#path_fmt);)
    } else {
        quote!(let __path = format!(#path_fmt, #(#path_args),*);)
    };

    let query_setters = op.query_params.iter().map(|p| {
        let ident = format_ident!("{}", snake_case(&p.name));
        let raw = &p.name;
        if p.required {
            quote!(__r = __r.query(&[(#raw, &#ident)]);)
        } else {
            quote!(
                if let Some(v) = &#ident {
                    __r = __r.query(&[(#raw, v)]);
                }
            )
        }
    });
    let header_setters = op.header_params.iter().map(|p| {
        let ident = format_ident!("{}", snake_case(&p.name));
        let raw = &p.name;
        if p.required {
            quote!(__r = __r.header(#raw, &#ident);)
        } else {
            quote!(
                if let Some(v) = &#ident {
                    __r = __r.header(#raw, v);
                }
            )
        }
    });

    let cookie_block = if op.cookie_params.is_empty() {
        quote!()
    } else {
        let pushes = op.cookie_params.iter().map(|p| {
            let ident = format_ident!("{}", snake_case(&p.name));
            let raw_eq = format!("{}={{}}", p.name);
            if p.required {
                quote!(__cookies.push(format!(#raw_eq, urlencoding::encode(&#ident)));)
            } else {
                quote!(
                    if let Some(v) = &#ident {
                        __cookies.push(format!(#raw_eq, urlencoding::encode(v)));
                    }
                )
            }
        });
        quote! {
            let mut __cookies: Vec<String> = Vec::new();
            #(#pushes)*
            if !__cookies.is_empty() {
                __r = __r.header("Cookie", __cookies.join("; "));
            }
        }
    };

    let body_block = match &op.request_body {
        Some(b) if b.required => quote! {
            let __body_value = parse_body_arg(&body).context("--body")?;
            __r = __r.json(&__body_value);
        },
        Some(_) => quote! {
            if let Some(s) = &body {
                let v = parse_body_arg(s).context("--body")?;
                __r = __r.json(&v);
            }
        },
        None => quote!(),
    };

    let doc_attr = first_line(op.documentation.as_deref())
        .map(|d| quote!(#[doc = #d]))
        .unwrap_or_default();

    quote! {
        #doc_attr
        pub async fn #method_ident(&self, #(#sig_args),*) -> Result<Value> {
            #path_decl
            let mut __r = self.req(__bearer, #http_method, &__path);
            #(#query_setters)*
            #(#header_setters)*
            #cookie_block
            #body_block
            let __resp = __r.send().await.context("sending request")?;
            let __status = __resp.status();
            let __text = __resp.text().await.context("reading response")?;
            let __json: Value = if __text.is_empty() {
                Value::Null
            } else {
                serde_json::from_str(&__text).unwrap_or(Value::String(__text.clone()))
            };
            if !__status.is_success() {
                return Err(anyhow!("HTTP {}: {}", __status, __json));
            }
            Ok(__json)
        }
    }
}

fn method_token(m: &HttpMethod) -> TokenStream {
    match m {
        HttpMethod::Get => quote!(reqwest::Method::GET),
        HttpMethod::Post => quote!(reqwest::Method::POST),
        HttpMethod::Put => quote!(reqwest::Method::PUT),
        HttpMethod::Delete => quote!(reqwest::Method::DELETE),
        HttpMethod::Patch => quote!(reqwest::Method::PATCH),
        HttpMethod::Options => quote!(reqwest::Method::OPTIONS),
        HttpMethod::Head => quote!(reqwest::Method::HEAD),
        HttpMethod::Trace => quote!(reqwest::Method::TRACE),
        // Mirror the previous string-emit behavior: unknown verbs fall
        // back to GET. (TODO: surface a diagnostic instead.)
        HttpMethod::Other(_) => quote!(reqwest::Method::GET),
    }
}

/// Walk a `/foo/{bar}/baz` style path, returning the printf-style
/// template and the expression list that fills it. Unknown `{x}`
/// placeholders (not in `path_params`) are passed through verbatim,
/// double-braced so `format!` doesn't try to interpolate them.
fn render_path_interpolation(
    template: &str,
    path_params: &[Parameter],
) -> (String, Vec<TokenStream>) {
    let mut out_template = String::with_capacity(template.len());
    let mut args = Vec::new();
    let mut chars = template.chars().peekable();
    while let Some(c) = chars.next() {
        if c == '{' {
            let mut name = String::new();
            for c2 in chars.by_ref() {
                if c2 == '}' {
                    break;
                }
                name.push(c2);
            }
            let snake = snake_case(&name);
            if path_params.iter().any(|p| snake_case(&p.name) == snake) {
                out_template.push_str("{}");
                let ident = format_ident!("{}", snake);
                args.push(quote!(urlencoding::encode(&#ident)));
            } else {
                // Pass through literal `{name}` — `format!` would
                // misinterpret a single brace, so double them.
                out_template.push_str("{{");
                out_template.push_str(&name);
                out_template.push_str("}}");
            }
        } else if c == '}' {
            // Standalone `}` is unusual but mirror upstream behavior.
            out_template.push('}');
        } else {
            out_template.push(c);
        }
    }
    (out_template, args)
}

// ---------------------------------------------------------------------------
// src/runtime.rs
// ---------------------------------------------------------------------------

fn emit_runtime_rs() -> String {
    RUNTIME_RS.into()
}

const RUNTIME_RS: &str = include_str!("../templates/runtime.rs.in");

// ---------------------------------------------------------------------------
// src/auth.rs
// ---------------------------------------------------------------------------

fn emit_auth_rs(bin_name: &str, oa: &OauthInfo, base_url_default: &str) -> String {
    let auth_url = oa.flow.authorization_url.as_deref().unwrap();
    let token_url = oa.flow.token_url.as_deref().unwrap();
    let client_id = &oa.config.client_id;
    let port = oa.config.redirect_port.unwrap_or(8848);
    let scopes_lit: String = oa
        .scopes
        .iter()
        .map(|s| format!("\"{}\"", escape_rust_string(s)))
        .collect::<Vec<_>>()
        .join(", ");
    let client_secret_env = oa.config.client_secret_env.as_deref().unwrap_or("");
    let exchange_active = oa.exchange.is_some();

    let mut composed = String::with_capacity(AUTH_RS_PROLOGUE.len() + AUTH_RS_EXCHANGE_TAIL.len());
    composed.push_str(AUTH_RS_PROLOGUE);
    if exchange_active {
        composed.push_str(AUTH_RS_EXCHANGE_TAIL);
    }

    composed
        .replace("__BIN_NAME__", bin_name)
        .replace("__CLIENT_ID__", &escape_rust_string(client_id))
        .replace("__AUTH_URL__", &escape_rust_string(auth_url))
        .replace("__TOKEN_URL__", &escape_rust_string(token_url))
        .replace(
            "__BASE_URL_DEFAULT__",
            &escape_rust_string(base_url_default),
        )
        .replace("__REDIRECT_PORT__", &port.to_string())
        .replace("__SCOPES__", &scopes_lit)
        .replace(
            "__CLIENT_SECRET_ENV__",
            &escape_rust_string(client_secret_env),
        )
        .replace("__PREFIX__", &env_prefix(bin_name))
}

const AUTH_RS_PROLOGUE: &str = include_str!("../templates/auth_prologue.rs.in");

const AUTH_RS_EXCHANGE_TAIL: &str = include_str!("../templates/auth_exchange_tail.rs.in");

// ---------------------------------------------------------------------------
// README.md
// ---------------------------------------------------------------------------

fn emit_readme(ir: &Ir, bin_name: &str, oauth: Option<&OauthInfo>) -> String {
    let prefix = env_prefix(bin_name);
    let oauth_section = if let Some(oa) = oauth {
        let mut s = format!(
            "\n## OAuth\n\nThis CLI was generated with OAuth 2.0 (PKCE authorization-code) wired up.\n\n```sh\n{bin_name} login    # opens a browser, persists the access token\n{bin_name} logout   # deletes the stored token\n```\n\nThe token is stored at the platform config dir under `{bin_name}/profiles/<profile>/auth.json` (mode 0600 on Unix).\nThe token is refreshed lazily on a 30-second skew.\n\n## Profiles (AWS-style)\n\nThe CLI bundles deployment-specific settings (URLs, client ID/secret) under named profiles in `<config_dir>/{bin_name}/config.toml`. The `default` profile is auto-populated from the spec on first run.\n\n```sh\n{bin_name} --profile dev <op>          # one-off override\n{prefix}_PROFILE=dev {bin_name} <op>    # via env\n```\n\nProfile fields are: `base_url`, `auth_url`, `token_url`, `client_id`, `client_secret`. Hand-edit `config.toml` for now (`{bin_name} configure` lands in a follow-up). Resolution chain per setting: `--<flag>` → `{prefix}_<NAME>` env → profile field → spec default.\n\nClient-secret resolution: per-profile literal `client_secret = \"...\"` → `{prefix}_CLIENT_SECRET` env (or the env var named in the generator's `oauth.clientSecretEnv`) → none. Storing the secret literally in `config.toml` matches the security posture of `~/.aws/credentials` (mode 0600 on Unix).\n\n### Targeting a different IdP host\n\n```sh\nexport {prefix}_AUTH_URL=https://auth.dev.example.com/realms/<realm>/protocol/openid-connect/auth\nexport {prefix}_TOKEN_URL=https://auth.dev.example.com/realms/<realm>/protocol/openid-connect/token\n```\n\nOr, more durably, edit the relevant profile in `config.toml`.\n"
        );
        if let Some(env) = oa
            .config
            .client_secret_env
            .as_deref()
            .filter(|s| !s.is_empty())
        {
            s.push_str(&format!(
                "\nThe configured OAuth client is **confidential** — set `{env}` to the client secret in your shell before running `{bin_name} login` (or any tenant-scoped operation).\n"
            ));
        }
        if let Some(ex) = &oa.exchange {
            let kebab = kebab_case(&ex.placeholder);
            s.push_str(&format!(
                "\n## Per-`{kebab}` token exchange (RFC 8693)\n\nOperations whose path includes `{{{ph}}}` use a tenant-scoped JWT minted via standard RFC 8693 token exchange against the IdP's token endpoint.\n\n```sh\n{bin_name} --{kebab} <slug> <op>           # one-off\n{bin_name} set-{kebab} <slug>                # persist a default (per active profile)\n{bin_name} unset-{kebab}                     # clear it (per active profile)\n{bin_name} show-{kebab}                      # show the current default\n```\n\n`set-{kebab}` writes to `<config_dir>/{bin_name}/profiles/<active>/{kebab}.json` — different profiles keep separate defaults.\n",
                ph = ex.placeholder,
            ));
        }
        s
    } else {
        String::new()
    };
    let completions_section = if oauth.is_some() {
        format!(
            "\n## Shell completions\n\nTwo flavors:\n\n### Static (subcommands + flags only)\n\n```sh\n# bash / zsh (current session)\nsource <({bin_name} completion bash)\nsource <({bin_name} completion zsh)\n\n# fish (current session) — fish has no <(...), pipe instead:\n{bin_name} completion fish | source\n\n# fish (persistent)\n{bin_name} completion fish > ~/.config/fish/completions/{bin_name}.fish\n```\n\nAlso supports `powershell` and `elvish`. Static scripts complete subcommand names and flag names; **they do not complete `--profile <TAB>` to known profile names** (the script doesn't dispatch back to the binary).\n\n### Dynamic (subcommands + flags + `--profile` values)\n\nAdd this to your shell init:\n\n```sh\n# bash\neval \"$(COMPLETE=bash {bin_name})\"\n\n# zsh\neval \"$(COMPLETE=zsh {bin_name})\"\n\n# fish\nCOMPLETE=fish {bin_name} | source\n```\n\nWith dynamic completion enabled, `{bin_name} --profile <TAB>` lists profile names from `config.toml` at completion time.\n"
        )
    } else {
        format!(
            "\n## Shell completions\n\n```sh\n# bash / zsh (current session)\nsource <({bin_name} completion bash)\nsource <({bin_name} completion zsh)\n\n# fish (current session) — fish has no <(...), pipe instead:\n{bin_name} completion fish | source\n\n# fish (persistent)\n{bin_name} completion fish > ~/.config/fish/completions/{bin_name}.fish\n```\n\nAlso supports `powershell` and `elvish`. Add to your shell init for persistence.\n"
        )
    };
    format!(
        "# {bin_name}\n\nGenerated by openapi-forge / generator-rust-clap.\n\nSpec: {title} v{version}\n\nOperations: {n}\n\n## Build\n\n```sh\ncargo build --release\n```\n\n## Auth\n\nBearer token via `--token <jwt>` or the env var `{prefix}_TOKEN`.\n{oauth_section}{completions_section}",
        title = ir.info.title,
        version = ir.info.version,
        n = ir.operations.len(),
    )
}

fn first_line(s: Option<&str>) -> Option<String> {
    s.and_then(|s| s.lines().next())
        .map(|l| l.trim().to_string())
        .filter(|s| !s.is_empty())
}

fn escape_rust_string(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn extract_placeholders_simple() {
        assert_eq!(
            extract_placeholders("urn:x:tenant:{tenant}"),
            vec!["tenant"]
        );
        assert_eq!(
            extract_placeholders("https://api/{a}/{b}/items"),
            vec!["a", "b"]
        );
        assert_eq!(extract_placeholders("static"), Vec::<String>::new());
    }

    #[test]
    fn auth_prologue_includes_write_profile_fields() {
        // Non-interactive configure flow depends on this helper being emitted.
        assert!(
            AUTH_RS_PROLOGUE.contains("pub fn write_profile_fields("),
            "auth.rs prologue must define write_profile_fields"
        );
        assert!(
            AUTH_RS_PROLOGUE.contains("client_secret: Option<String>,"),
            "write_profile_fields must accept Option<String> for each field"
        );
    }

    #[test]
    fn configure_variant_exposes_non_interactive_flags() {
        // Empty tag tree is enough to drive emit_root_enum into the oauth branch.
        let tree = TagTree { roots: vec![] };
        let tokens = emit_root_enum(&tree, /*oauth_active*/ true, None, None, None);
        // TokenStream → String drops formatting but preserves identifiers
        // and punctuation, which is all this test asserts on.
        let out = tokens.to_string();
        // Struct-form Configure with each scriptable field + the bypass flag.
        // Field syntax round-trips through quote! as `name : ty ,` (with spaces),
        // so assert on the field identifiers separately from their types.
        assert!(
            out.contains("Configure"),
            "missing Configure variant:\n{out}"
        );
        for needle in [
            "base_url",
            "auth_url",
            "token_url",
            "client_id",
            "client_secret",
            "non_interactive",
        ] {
            assert!(
                out.contains(needle),
                "emitted Cmd enum missing `{needle}`:\n{out}"
            );
        }
    }
}
