//! Render one Kotlin source file (all NamedTypes that share an output path).

use std::collections::BTreeSet;
use std::fmt::{self, Write};

use forge_plugin_sdk::ir::{
    AdditionalProperties, Ir, NamedType, PrimitiveKind, TypeDef, TypeRef, UnionType,
};
use forge_plugin_sdk::{types_ext, values_ext};
use serde_json::Value as JsonValue;

use crate::emit::{
    effective_discriminator, is_synthetic_id, FqcnIndex, NestingTree, VariantIndex, VariantInfo,
};
use crate::naming::{enum_variant_ident, property_ident};

#[derive(Debug)]
pub enum RenderError {
    /// Underlying primitive cannot be wrapped as a values4k Value.
    Unsupported(String),
}

impl fmt::Display for RenderError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            RenderError::Unsupported(msg) => write!(f, "{msg}"),
        }
    }
}

pub struct FileRender {
    pub path: String,
    pub source: String,
}

/// Render one file containing every `NamedType` in `types` that resolved to
/// `path`. Imports are computed from the cross-package references encountered
/// while rendering each body.
pub fn render_file(
    spec: &Ir,
    index: &FqcnIndex,
    variants: &VariantIndex,
    nest: &NestingTree,
    path: &str,
    types: &[&NamedType],
) -> Result<FileRender, RenderError> {
    // The file's Kotlin `package` declaration is the package of one of the
    // tree roots — i.e. the FQCN segments up to the last `.`. All roots in a
    // file should share a package (the build_nesting_tree contract); if they
    // disagree (misconfigured spec) the first root's package wins.
    let first_root = *nest
        .roots
        .first()
        .ok_or_else(|| RenderError::Unsupported(format!("no top-level types resolved for {path}")))?;
    let first_root_target = index
        .get(first_root)
        .expect("nesting tree roots come from the FqcnIndex");
    // Split the parsed package into (effective Kotlin package, phantom
    // wrapper-class segments). Phantom segments are PascalCase suffixes
    // that have no indexed schema — but the FQCN convention is
    // `ca.dialai.X.Y` = `class X { class Y { ... } }`, so we materialize an
    // empty `class X { ... }` wrapper rather than dropping the segment.
    let (package, auto_wrappers) =
        split_phantom_wrappers(&first_root_target.target.package, index);

    let mut ctx = FileCtx::new(&package, spec, index, variants);

    let mut bodies = String::new();
    for root_id in &nest.roots {
        let Some(named) = types.iter().find(|t| t.id.as_str() == *root_id).copied() else {
            continue;
        };
        let body = render_with_nested(&mut ctx, named, nest, types)?;
        if !bodies.is_empty() {
            bodies.push('\n');
        }
        bodies.push_str(&body);
    }

    // Wrap roots in any phantom outer classes — innermost first so we build
    // up `class Outer { class Inner { ...roots... } }` correctly.
    for wrapper in &auto_wrappers {
        let mut wrapped = String::new();
        // Phantom auto-wrappers exist purely to group children that share a
        // FQCN prefix without an explicit schema for the outer name. Match
        // the default `internal` visibility so they don't leak across
        // module boundaries by accident.
        let _ = writeln!(wrapped, "internal class {wrapper} {{");
        for line in bodies.lines() {
            if line.is_empty() {
                wrapped.push('\n');
            } else {
                let _ = writeln!(wrapped, "    {line}");
            }
        }
        let _ = writeln!(wrapped, "}}");
        bodies = wrapped;
    }

    let mut out = String::new();
    let _ = writeln!(out, "// Generated by generator-kotlin-types — do not edit.");
    if !ctx.use_serializers.is_empty() {
        // @file:UseSerializers wires the per-type serializers we emit at the
        // bottom of this file to every inline use of the underlying java.time
        // (or ByteArray) value. Saves a per-field @Serializable annotation at
        // every property site. Must precede the `package` line.
        let names: Vec<String> = ctx
            .use_serializers
            .iter()
            .map(|k| format!("{}::class", k.object_name()))
            .collect();
        let _ = writeln!(out, "@file:UseSerializers({})", names.join(", "));
        out.push('\n');
        ctx.imports.add("kotlinx.serialization.UseSerializers");
    }
    let _ = writeln!(out, "package {}", package);
    out.push('\n');
    let serializers = std::mem::take(&mut ctx.serializers_to_emit);
    let imports = ctx.imports.finish();
    if !imports.is_empty() {
        for line in imports {
            let _ = writeln!(out, "import {line}");
        }
        out.push('\n');
    }
    out.push_str(&bodies);
    for kind in &serializers {
        out.push('\n');
        out.push_str(kind.source());
    }

    Ok(FileRender {
        path: path.to_string(),
        source: out,
    })
}

// ---- file-scoped context for imports & inline-serializer tracking ----

struct FileCtx<'a> {
    package: &'a str,
    spec: &'a Ir,
    index: &'a FqcnIndex<'a>,
    variants: &'a VariantIndex<'a>,
    imports: ImportSet,
    /// Serializer objects that must be defined inline at the end of the file.
    /// A named wrapper (e.g. `CreatedAt` delegating to `OffsetDateTimeSerializer`)
    /// adds to this set without adding to `use_serializers`.
    serializers_to_emit: BTreeSet<SerKind>,
    /// Subset of `serializers_to_emit` that must also be wired up via
    /// `@file:UseSerializers(...)` so inline property uses of the underlying
    /// type (e.g. `val createdAt: OffsetDateTime`) round-trip without a per-field
    /// annotation. Only the inline path adds here; the wrapped path does not.
    use_serializers: BTreeSet<SerKind>,
}

impl<'a> FileCtx<'a> {
    fn new(
        package: &'a str,
        spec: &'a Ir,
        index: &'a FqcnIndex<'a>,
        variants: &'a VariantIndex<'a>,
    ) -> Self {
        Self {
            package,
            spec,
            index,
            variants,
            imports: ImportSet::default(),
            serializers_to_emit: BTreeSet::new(),
            use_serializers: BTreeSet::new(),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
enum SerKind {
    /// `format: date-time` — RFC 3339 with offset preserved.
    OffsetDateTime,
    /// `format: instant` — a fixed UTC point in time (no offset info).
    Instant,
    LocalDate,
    LocalTime,
    Uuid,
    Base64Bytes,
}

impl SerKind {
    fn object_name(self) -> &'static str {
        match self {
            SerKind::OffsetDateTime => "OffsetDateTimeSerializer",
            SerKind::Instant => "InstantSerializer",
            SerKind::LocalDate => "LocalDateSerializer",
            SerKind::LocalTime => "LocalTimeSerializer",
            SerKind::Uuid => "UuidSerializer",
            SerKind::Base64Bytes => "Base64ByteArraySerializer",
        }
    }
    fn source(self) -> &'static str {
        match self {
            SerKind::OffsetDateTime => OFFSET_DATE_TIME_SERIALIZER,
            SerKind::Instant => INSTANT_SERIALIZER,
            SerKind::LocalDate => LOCAL_DATE_SERIALIZER,
            SerKind::LocalTime => LOCAL_TIME_SERIALIZER,
            SerKind::Uuid => UUID_SERIALIZER,
            SerKind::Base64Bytes => BASE64_BYTES_SERIALIZER,
        }
    }
}

#[derive(Default)]
struct ImportSet {
    items: BTreeSet<String>,
}

impl ImportSet {
    fn add(&mut self, fqcn: impl Into<String>) {
        self.items.insert(fqcn.into());
    }
    fn finish(self) -> Vec<String> {
        self.items.into_iter().collect()
    }
}

// ---- per-NamedType dispatch ----

/// Render `named` as a Kotlin source unit, plus recursively render every
/// FQCN-child (entries in `nest.children[named.id]`) and embed those rendered
/// bodies inside the parent's `{ ... }` block. Pure object/union/enum
/// parents can carry nested classes; value-wrappers / typealiases / arrays
/// cannot, and surface a `RenderError::Unsupported` when nesting is asked of
/// them.
fn render_with_nested(
    ctx: &mut FileCtx,
    named: &NamedType,
    nest: &NestingTree,
    types: &[&NamedType],
) -> Result<String, RenderError> {
    // Render children first so they can populate `ctx.imports` /
    // `ctx.serializers_to_emit` before the parent writes its body.
    let mut child_bodies: Vec<String> = Vec::new();
    if let Some(children) = nest.children.get(named.id.as_str()) {
        for child_id in children {
            let Some(child) = types.iter().find(|t| t.id.as_str() == *child_id).copied() else {
                continue;
            };
            let body = render_with_nested(ctx, child, nest, types)?;
            child_bodies.push(body);
        }
    }
    render_named(ctx, named, &child_bodies)
}

fn render_named(
    ctx: &mut FileCtx,
    named: &NamedType,
    fqcn_children: &[String],
) -> Result<String, RenderError> {
    let resolved = ctx
        .index
        .get(named.id.as_str())
        .expect("render_named called on un-indexed type");
    let class_name = resolved.target.class_name.clone();
    let vis = resolved.visibility.modifier();

    match &named.definition {
        TypeDef::Primitive(p) => {
            reject_nesting(&class_name, "primitive value wrapper", fqcn_children)?;
            render_value_object(ctx, &class_name, vis, named, p)
        }
        TypeDef::Object(o) => render_object(ctx, &class_name, vis, named, o, fqcn_children),
        TypeDef::EnumString(e) => render_enum_string(ctx, &class_name, vis, e, fqcn_children),
        TypeDef::EnumInt(e) => {
            reject_nesting(&class_name, "integer enum", fqcn_children)?;
            render_enum_int(ctx, &class_name, vis, e)
        }
        TypeDef::Union(u) => render_union(ctx, &class_name, vis, named, u, fqcn_children),
        TypeDef::Array(_) => {
            reject_nesting(&class_name, "array typealias", fqcn_children)?;
            render_array_alias(ctx, &class_name, vis, named)
        }
        TypeDef::Null => Err(RenderError::Unsupported(
            "the null type cannot be rendered as a Kotlin class".into(),
        )),
    }
}

fn reject_nesting(
    class_name: &str,
    shape: &str,
    fqcn_children: &[String],
) -> Result<(), RenderError> {
    if fqcn_children.is_empty() {
        return Ok(());
    }
    Err(RenderError::Unsupported(format!(
        "'{class_name}' is a {shape}; Kotlin doesn't allow nested classes inside it. \
         Move the FQCN children to a sibling file, or change '{class_name}' to an object/sealed/enum"
    )))
}

// ---- value object (values4k wrapper) ----

fn render_value_object(
    ctx: &mut FileCtx,
    class_name: &str,
    vis: &str,
    named: &NamedType,
    p: &forge_plugin_sdk::ir::PrimitiveType,
) -> Result<String, RenderError> {
    // Special-format string primitives don't fit the values4k *Value model.
    // Wrap the matching JVM type with our inlined per-format KSerializer.
    if matches!(p.kind, PrimitiveKind::String) {
        match p.constraints.format_extension.as_deref() {
            Some("date-time") => {
                return Ok(render_special_wrapper(ctx, class_name, vis, SerKind::OffsetDateTime));
            }
            Some("instant") => {
                return Ok(render_special_wrapper(ctx, class_name, vis, SerKind::Instant));
            }
            Some("date") => {
                return Ok(render_special_wrapper(ctx, class_name, vis, SerKind::LocalDate));
            }
            Some("time") => {
                return Ok(render_special_wrapper(ctx, class_name, vis, SerKind::LocalTime));
            }
            Some("uuid") => {
                return Ok(render_special_wrapper(ctx, class_name, vis, SerKind::Uuid));
            }
            Some("byte") => {
                return Ok(render_byte_wrapper(ctx, class_name, vis));
            }
            _ => {}
        }
    }

    let plan = ValuePlan::for_primitive(ctx.spec, p)?;
    ctx.imports.add("kotlinx.serialization.KSerializer");
    ctx.imports.add("kotlinx.serialization.Serializable");
    ctx.imports
        .add("kotlinx.serialization.descriptors.PrimitiveKind");
    ctx.imports
        .add("kotlinx.serialization.descriptors.PrimitiveSerialDescriptor");
    ctx.imports.add("kotlinx.serialization.encoding.Decoder");
    ctx.imports.add("kotlinx.serialization.encoding.Encoder");
    ctx.imports.add(format!("dev.forkhandles.values.{}", plan.base_class));
    ctx.imports
        .add(format!("dev.forkhandles.values.{}", plan.factory_class));
    for ext in &plan.validation_extensions {
        ctx.imports.add(format!("dev.forkhandles.values.{}", ext));
    }

    let factory_arg = plan.validation_expr();
    let factory_line = match factory_arg {
        Some(expr) => format!(
            "    companion object : {factory}<{cls}>(::{cls}, {expr})",
            factory = plan.factory_class,
            cls = class_name,
            expr = expr
        ),
        None => format!(
            "    companion object : {factory}<{cls}>(::{cls})",
            factory = plan.factory_class,
            cls = class_name
        ),
    };

    let underlying_kt = plan.underlying_kt;
    let descriptor_kind = plan.descriptor_kind;
    let encode_call = plan.encode_call;
    let decode_call = plan.decode_call;

    let mut out = String::new();
    if let Some(doc) = doc_block(named) {
        out.push_str(&doc);
    }
    let _ = writeln!(
        out,
        "@Serializable(with = {class_name}.Serializer::class)\n\
         {vis}data class {class_name} private constructor(val value: {underlying_kt}) : {base}(value) {{",
        base = plan.base_class
    );
    let _ = writeln!(out, "{factory_line}");
    out.push('\n');
    let _ = writeln!(
        out,
        "    internal object Serializer : KSerializer<{class_name}> {{\n\
            \x20       override val descriptor = PrimitiveSerialDescriptor(\"{class_name}\", PrimitiveKind.{descriptor_kind})\n\
            \x20       override fun serialize(encoder: Encoder, value: {class_name}) = encoder.{encode_call}(value.value)\n\
            \x20       override fun deserialize(decoder: Decoder): {class_name} = {class_name}.of(decoder.{decode_call}())\n\
            \x20   }}"
    );
    out.push_str("}\n");
    Ok(out)
}

fn render_special_wrapper(
    ctx: &mut FileCtx,
    class_name: &str,
    vis: &str,
    kind: SerKind,
) -> String {
    ctx.imports.add("kotlinx.serialization.KSerializer");
    ctx.imports.add("kotlinx.serialization.Serializable");
    ctx.imports
        .add("kotlinx.serialization.descriptors.PrimitiveKind");
    ctx.imports
        .add("kotlinx.serialization.descriptors.PrimitiveSerialDescriptor");
    ctx.imports.add("kotlinx.serialization.encoding.Decoder");
    ctx.imports.add("kotlinx.serialization.encoding.Encoder");
    let underlying = match kind {
        SerKind::OffsetDateTime => {
            ctx.imports.add("java.time.OffsetDateTime");
            "OffsetDateTime"
        }
        SerKind::Instant => {
            ctx.imports.add("java.time.Instant");
            "Instant"
        }
        SerKind::LocalDate => {
            ctx.imports.add("java.time.LocalDate");
            "LocalDate"
        }
        SerKind::LocalTime => {
            ctx.imports.add("java.time.LocalTime");
            "LocalTime"
        }
        SerKind::Uuid => {
            ctx.imports.add("java.util.UUID");
            "UUID"
        }
        SerKind::Base64Bytes => unreachable!("byte → render_byte_wrapper"),
    };
    // The wrapped path only needs the serializer object itself (not the
    // @file:UseSerializers directive — the wrapper's own KSerializer takes
    // over for `class_name`, and the underlying type only appears inside the
    // wrapper's body, never as a free-standing inline property).
    ctx.serializers_to_emit.insert(kind);
    let helper = kind.object_name();

    let mut out = String::new();
    let _ = writeln!(
        out,
        "@Serializable(with = {class_name}.Serializer::class)\n\
         {vis}data class {class_name}(val value: {underlying}) {{\n\
            \x20   internal object Serializer : KSerializer<{class_name}> by {helper}.map({class_name}::value, ::{class_name})\n\
         }}"
    );
    out
}

/// Wrap `type: string, format: byte` (Base64-encoded bytes) as a `ByteArray`
/// data class. values4k has no `ByteArrayValue`, so this doesn't inherit a
/// `*Value` base — but it keeps the rest of the pattern (private constructor,
/// `of(...)` factory, custom `KSerializer` that round-trips through a JSON
/// Base64 string).
fn render_byte_wrapper(ctx: &mut FileCtx, class_name: &str, vis: &str) -> String {
    ctx.imports.add("kotlinx.serialization.KSerializer");
    ctx.imports.add("kotlinx.serialization.Serializable");
    ctx.imports
        .add("kotlinx.serialization.descriptors.PrimitiveKind");
    ctx.imports
        .add("kotlinx.serialization.descriptors.PrimitiveSerialDescriptor");
    ctx.imports.add("kotlinx.serialization.encoding.Decoder");
    ctx.imports.add("kotlinx.serialization.encoding.Encoder");
    let mut out = String::new();
    let _ = writeln!(
        out,
        "@Serializable(with = {class_name}.Serializer::class)\n\
         {vis}data class {class_name} private constructor(val value: ByteArray) {{\n\
            \x20   companion object {{ fun of(value: ByteArray): {class_name} = {class_name}(value) }}\n\
         \n\
            \x20   internal object Serializer : KSerializer<{class_name}> {{\n\
            \x20       override val descriptor = PrimitiveSerialDescriptor(\"{class_name}\", PrimitiveKind.STRING)\n\
            \x20       override fun serialize(encoder: Encoder, value: {class_name}) =\n\
            \x20           encoder.encodeString(java.util.Base64.getEncoder().encodeToString(value.value))\n\
            \x20       override fun deserialize(decoder: Decoder): {class_name} =\n\
            \x20           {class_name}(java.util.Base64.getDecoder().decode(decoder.decodeString()))\n\
            \x20   }}\n\
         }}"
    );
    out
}

const OFFSET_DATE_TIME_SERIALIZER: &str = "private object OffsetDateTimeSerializer : KSerializer<java.time.OffsetDateTime> {\n    override val descriptor = PrimitiveSerialDescriptor(\"java.time.OffsetDateTime\", PrimitiveKind.STRING)\n    override fun serialize(encoder: Encoder, value: java.time.OffsetDateTime) = encoder.encodeString(value.toString())\n    override fun deserialize(decoder: Decoder): java.time.OffsetDateTime = java.time.OffsetDateTime.parse(decoder.decodeString())\n    fun <T> map(get: (T) -> java.time.OffsetDateTime, build: (java.time.OffsetDateTime) -> T): KSerializer<T> = object : KSerializer<T> {\n        override val descriptor = this@OffsetDateTimeSerializer.descriptor\n        override fun serialize(encoder: Encoder, value: T) = this@OffsetDateTimeSerializer.serialize(encoder, get(value))\n        override fun deserialize(decoder: Decoder): T = build(this@OffsetDateTimeSerializer.deserialize(decoder))\n    }\n}\n";

const INSTANT_SERIALIZER: &str = "private object InstantSerializer : KSerializer<java.time.Instant> {\n    override val descriptor = PrimitiveSerialDescriptor(\"java.time.Instant\", PrimitiveKind.STRING)\n    override fun serialize(encoder: Encoder, value: java.time.Instant) = encoder.encodeString(value.toString())\n    override fun deserialize(decoder: Decoder): java.time.Instant = java.time.Instant.parse(decoder.decodeString())\n    fun <T> map(get: (T) -> java.time.Instant, build: (java.time.Instant) -> T): KSerializer<T> = object : KSerializer<T> {\n        override val descriptor = this@InstantSerializer.descriptor\n        override fun serialize(encoder: Encoder, value: T) = this@InstantSerializer.serialize(encoder, get(value))\n        override fun deserialize(decoder: Decoder): T = build(this@InstantSerializer.deserialize(decoder))\n    }\n}\n";

const LOCAL_DATE_SERIALIZER: &str = "private object LocalDateSerializer : KSerializer<java.time.LocalDate> {\n    override val descriptor = PrimitiveSerialDescriptor(\"java.time.LocalDate\", PrimitiveKind.STRING)\n    override fun serialize(encoder: Encoder, value: java.time.LocalDate) = encoder.encodeString(value.toString())\n    override fun deserialize(decoder: Decoder): java.time.LocalDate = java.time.LocalDate.parse(decoder.decodeString())\n    fun <T> map(get: (T) -> java.time.LocalDate, build: (java.time.LocalDate) -> T): KSerializer<T> = object : KSerializer<T> {\n        override val descriptor = this@LocalDateSerializer.descriptor\n        override fun serialize(encoder: Encoder, value: T) = this@LocalDateSerializer.serialize(encoder, get(value))\n        override fun deserialize(decoder: Decoder): T = build(this@LocalDateSerializer.deserialize(decoder))\n    }\n}\n";

const LOCAL_TIME_SERIALIZER: &str = "private object LocalTimeSerializer : KSerializer<java.time.LocalTime> {\n    override val descriptor = PrimitiveSerialDescriptor(\"java.time.LocalTime\", PrimitiveKind.STRING)\n    override fun serialize(encoder: Encoder, value: java.time.LocalTime) = encoder.encodeString(value.toString())\n    override fun deserialize(decoder: Decoder): java.time.LocalTime = java.time.LocalTime.parse(decoder.decodeString())\n    fun <T> map(get: (T) -> java.time.LocalTime, build: (java.time.LocalTime) -> T): KSerializer<T> = object : KSerializer<T> {\n        override val descriptor = this@LocalTimeSerializer.descriptor\n        override fun serialize(encoder: Encoder, value: T) = this@LocalTimeSerializer.serialize(encoder, get(value))\n        override fun deserialize(decoder: Decoder): T = build(this@LocalTimeSerializer.deserialize(decoder))\n    }\n}\n";

const UUID_SERIALIZER: &str = "private object UuidSerializer : KSerializer<java.util.UUID> {\n    override val descriptor = PrimitiveSerialDescriptor(\"java.util.UUID\", PrimitiveKind.STRING)\n    override fun serialize(encoder: Encoder, value: java.util.UUID) = encoder.encodeString(value.toString())\n    override fun deserialize(decoder: Decoder): java.util.UUID = java.util.UUID.fromString(decoder.decodeString())\n    fun <T> map(get: (T) -> java.util.UUID, build: (java.util.UUID) -> T): KSerializer<T> = object : KSerializer<T> {\n        override val descriptor = this@UuidSerializer.descriptor\n        override fun serialize(encoder: Encoder, value: T) = this@UuidSerializer.serialize(encoder, get(value))\n        override fun deserialize(decoder: Decoder): T = build(this@UuidSerializer.deserialize(decoder))\n    }\n}\n";

const BASE64_BYTES_SERIALIZER: &str = "private object Base64ByteArraySerializer : KSerializer<ByteArray> {\n    override val descriptor = PrimitiveSerialDescriptor(\"Base64ByteArray\", PrimitiveKind.STRING)\n    override fun serialize(encoder: Encoder, value: ByteArray) =\n        encoder.encodeString(java.util.Base64.getEncoder().encodeToString(value))\n    override fun deserialize(decoder: Decoder): ByteArray =\n        java.util.Base64.getDecoder().decode(decoder.decodeString())\n}\n";

struct ValuePlan {
    base_class: &'static str,
    factory_class: &'static str,
    underlying_kt: &'static str,
    descriptor_kind: &'static str,
    encode_call: &'static str,
    decode_call: &'static str,
    /// Validation expressions joined into a single argument passed to the
    /// factory base. `None` produces a single-arg companion (no validation).
    validation_expr_parts: Vec<String>,
    validation_extensions: Vec<&'static str>,
}

impl ValuePlan {
    fn for_primitive(
        spec: &Ir,
        p: &forge_plugin_sdk::ir::PrimitiveType,
    ) -> Result<Self, RenderError> {
        let (base, factory, underlying, kind, encode, decode) = match p.kind {
            PrimitiveKind::String => (
                "StringValue",
                "StringValueFactory",
                "String",
                "STRING",
                "encodeString",
                "decodeString",
            ),
            PrimitiveKind::Bool => (
                "BooleanValue",
                "BooleanValueFactory",
                "Boolean",
                "BOOLEAN",
                "encodeBoolean",
                "decodeBoolean",
            ),
            PrimitiveKind::Integer => match p.constraints.format_extension.as_deref() {
                Some("int32") => (
                    "IntValue",
                    "IntValueFactory",
                    "Int",
                    "INT",
                    "encodeInt",
                    "decodeInt",
                ),
                _ => (
                    "LongValue",
                    "LongValueFactory",
                    "Long",
                    "LONG",
                    "encodeLong",
                    "decodeLong",
                ),
            },
            PrimitiveKind::Number => match p.constraints.format_extension.as_deref() {
                Some("float") => (
                    "FloatValue",
                    "FloatValueFactory",
                    "Float",
                    "FLOAT",
                    "encodeFloat",
                    "decodeFloat",
                ),
                _ => (
                    "DoubleValue",
                    "DoubleValueFactory",
                    "Double",
                    "DOUBLE",
                    "encodeDouble",
                    "decodeDouble",
                ),
            },
        };

        let mut parts: Vec<String> = Vec::new();
        let mut extensions: Vec<&'static str> = Vec::new();

        match p.kind {
            PrimitiveKind::String => {
                if let Some(min) = p.constraints.min_length {
                    parts.push(format!("{min}.minLength"));
                    extensions.push("minLength");
                }
                if let Some(max) = p.constraints.max_length {
                    parts.push(format!("{max}.maxLength"));
                    extensions.push("maxLength");
                }
                if let Some(pat) = &p.constraints.pattern {
                    parts.push(format!("\"{}\".regex", escape_kotlin_string(pat)));
                    extensions.push("regex");
                }
            }
            PrimitiveKind::Integer | PrimitiveKind::Number => {
                let suffix = if matches!(p.kind, PrimitiveKind::Integer)
                    && p.constraints.format_extension.as_deref() != Some("int32")
                {
                    "L"
                } else {
                    ""
                };
                if let Some(min) = resolve_numeric_literal(spec, p.constraints.minimum, suffix) {
                    parts.push(format!("{min}.minValue"));
                    extensions.push("minValue");
                }
                if let Some(max) = resolve_numeric_literal(spec, p.constraints.maximum, suffix) {
                    parts.push(format!("{max}.maxValue"));
                    extensions.push("maxValue");
                }
                if let Some(min) =
                    resolve_numeric_literal(spec, p.constraints.exclusive_minimum, suffix)
                {
                    parts.push(format!("{min}.exclusiveMinValue"));
                    extensions.push("exclusiveMinValue");
                }
                if let Some(max) =
                    resolve_numeric_literal(spec, p.constraints.exclusive_maximum, suffix)
                {
                    parts.push(format!("{max}.exclusiveMaxValue"));
                    extensions.push("exclusiveMaxValue");
                }
            }
            PrimitiveKind::Bool => {}
        }

        Ok(ValuePlan {
            base_class: base,
            factory_class: factory,
            underlying_kt: underlying,
            descriptor_kind: kind,
            encode_call: encode,
            decode_call: decode,
            validation_expr_parts: parts,
            validation_extensions: extensions,
        })
    }

    fn validation_expr(&self) -> Option<String> {
        if self.validation_expr_parts.is_empty() {
            return None;
        }
        Some(self.validation_expr_parts.join(".and("))
            .map(|s| {
                let closes = self.validation_expr_parts.len().saturating_sub(1);
                let mut s = s;
                for _ in 0..closes {
                    s.push(')');
                }
                s
            })
    }
}

fn resolve_numeric_literal(
    spec: &Ir,
    vref: Option<forge_plugin_sdk::ir::ValueRef>,
    suffix: &str,
) -> Option<String> {
    let r = vref?;
    match values_ext::resolve_to_serde(&spec.values, r) {
        JsonValue::Number(n) => {
            if let Some(i) = n.as_i64() {
                Some(format!("{i}{suffix}"))
            } else if let Some(u) = n.as_u64() {
                Some(format!("{u}{suffix}"))
            } else {
                n.as_f64().map(|f| format!("{f}"))
            }
        }
        _ => None,
    }
}

// ---- object ----

fn render_object(
    ctx: &mut FileCtx,
    class_name: &str,
    vis: &str,
    named: &NamedType,
    obj: &forge_plugin_sdk::ir::ObjectType,
    fqcn_children: &[String],
) -> Result<String, RenderError> {
    ctx.imports.add("kotlinx.serialization.Serializable");

    // If this object is a variant of a discriminated union, the
    // discriminator property is owned by kotlinx.serialization — we MUST
    // omit it from the data class to avoid double-encoding it.
    let variant: Option<VariantInfo> = ctx.variants.get(named.id.as_str()).cloned();

    let mut out = String::new();
    if let Some(doc) = doc_block(named) {
        out.push_str(&doc);
    }

    if let Some(v) = &variant {
        let (parent_pkg, parent_wrappers) =
            split_phantom_wrappers(&v.parent_package, ctx.index);
        if parent_pkg != ctx.package {
            let mut fqcn = parent_pkg;
            for w in parent_wrappers.iter().rev() {
                fqcn.push('.');
                fqcn.push_str(w);
            }
            fqcn.push('.');
            fqcn.push_str(&v.parent_class);
            ctx.imports.add(fqcn);
        }
        let _ = writeln!(out, "@Serializable");
        if let Some(tag) = &v.serial_name {
            ctx.imports.add("kotlinx.serialization.SerialName");
            let _ = writeln!(out, "@SerialName(\"{}\")", escape_kotlin_string(tag));
        }
    } else {
        let _ = writeln!(out, "@Serializable");
    }

    let visible: Vec<&forge_plugin_sdk::ir::Property> = obj
        .properties
        .iter()
        .filter(|p| match &variant {
            // Drop the discriminator property only when there is one — for
            // untagged single-variant inheritance every property survives.
            Some(VariantInfo {
                discriminator: Some(d),
                ..
            }) => &p.name != d,
            _ => true,
        })
        .collect();

    let parent_marker = variant
        .as_ref()
        .map(|v| format!(" : {}", v.parent_class))
        .unwrap_or_default();

    if visible.is_empty() {
        // Object with no fields to render. If it's a discriminator variant,
        // we still want `data class Foo : Animal` form — but Kotlin requires
        // at least one parameter for `data class`. Fall back to a plain
        // `object` for the no-prop variant case.
        match (variant.is_some(), &obj.additional_properties) {
            (true, _) => {
                if fqcn_children.is_empty() {
                    let _ = writeln!(out, "{vis}object {class_name}{parent_marker}");
                } else {
                    let _ = writeln!(out, "{vis}object {class_name}{parent_marker} {{");
                    write_indented_blocks(&mut out, fqcn_children);
                    let _ = writeln!(out, "}}");
                }
            }
            (false, AdditionalProperties::Typed { r#type }) => {
                reject_nesting(class_name, "map typealias", fqcn_children)?;
                let value_kt = resolve_type(ctx, r#type)?;
                let _ = writeln!(out, "{vis}typealias {class_name} = Map<String, {value_kt}>");
            }
            (false, _) => {
                if fqcn_children.is_empty() {
                    let _ = writeln!(out, "{vis}class {class_name}");
                } else {
                    let _ = writeln!(out, "{vis}class {class_name} {{");
                    write_indented_blocks(&mut out, fqcn_children);
                    let _ = writeln!(out, "}}");
                }
            }
        }
        return Ok(out);
    }

    let _ = writeln!(out, "{vis}data class {class_name}(");
    let mut nested_bodies: Vec<String> = fqcn_children.to_vec();
    let last = visible.len() - 1;
    for (i, prop) in visible.iter().enumerate() {
        let (kotlin_name, oas_name) = property_ident(&prop.name);
        if kotlin_name != oas_name {
            ctx.imports.add("kotlinx.serialization.SerialName");
            let _ = writeln!(out, "    @SerialName(\"{}\")", oas_name);
        }
        let prop_ty = property_type(ctx, prop, &mut nested_bodies)?;
        let trailing = if i == last { "," } else { "," };
        let prop_ty_optional = if !prop.required && !prop_ty.ends_with('?') {
            format!("{prop_ty}?")
        } else {
            prop_ty
        };
        let default = if !prop.required { " = null" } else { "" };
        let _ = writeln!(
            out,
            "    val {kotlin_name}: {prop_ty_optional}{default}{trailing}"
        );
    }
    if nested_bodies.is_empty() {
        let _ = writeln!(out, "){parent_marker}");
    } else {
        let _ = writeln!(out, "){parent_marker} {{");
        write_indented_blocks(&mut out, &nested_bodies);
        let _ = writeln!(out, "}}");
    }
    Ok(out)
}

/// Split a parsed FQCN package into `(effective Kotlin package, phantom
/// wrapper-class segments)`. A "phantom" segment is a PascalCase suffix that
/// has no indexed schema — the spec's FQCN convention is `ca.dialai.X.Y` =
/// `class X { class Y { ... } }`, so when `X` has no annotated schema we still
/// materialize an empty `class X { ... }` wrapper at render time rather than
/// dropping the segment. Wrapper names are returned innermost-first so the
/// caller can fold them around the rendered body in order.
fn split_phantom_wrappers(package: &str, index: &FqcnIndex) -> (String, Vec<String>) {
    let indexed_fqcns: BTreeSet<String> =
        index.values().map(|t| t.target.fqcn()).collect();
    let mut segments: Vec<&str> = package.split('.').collect();
    let mut wrappers: Vec<String> = Vec::new();
    while let Some(last) = segments.last().copied() {
        let starts_upper = last
            .chars()
            .next()
            .map(|c| c.is_ascii_uppercase())
            .unwrap_or(false);
        if !starts_upper {
            break;
        }
        let prefix = segments.join(".");
        if indexed_fqcns.contains(&prefix) {
            break;
        }
        wrappers.push(last.to_string());
        segments.pop();
    }
    (segments.join("."), wrappers)
}

/// Append every block in `bodies` to `out`, indenting each non-empty line by
/// four spaces. Used to embed nested-class declarations inside an outer
/// class's `{ ... }` body. Bodies passed in are themselves full class
/// declarations (with their own already-indented inner content).
fn write_indented_blocks(out: &mut String, bodies: &[String]) {
    for body in bodies {
        for line in body.lines() {
            if line.is_empty() {
                out.push('\n');
            } else {
                let _ = writeln!(out, "    {line}");
            }
        }
    }
}

fn property_type(
    ctx: &mut FileCtx,
    prop: &forge_plugin_sdk::ir::Property,
    nested_bodies: &mut Vec<String>,
) -> Result<String, RenderError> {
    if let Some(name) = try_promote_to_nested(ctx, &prop.name, &prop.r#type, nested_bodies)? {
        return Ok(name);
    }
    resolve_type(ctx, &prop.r#type)
}

/// Look at the property's resolved type; if it's a synthetic object (one the
/// forge IR generated from an inline `{ type: object, properties: {...} }`
/// schema), promote it to a nested class inside the current outer class.
/// The nested class's simple name is the property name in PascalCase.
/// Returns `Some(nested_simple_name)` when promotion fires; `None` otherwise
/// (caller falls back to the normal `resolve_type` path).
fn try_promote_to_nested(
    ctx: &mut FileCtx,
    prop_name: &str,
    type_ref: &TypeRef,
    nested_bodies: &mut Vec<String>,
) -> Result<Option<String>, RenderError> {
    let Some(named) = ctx.spec.types.iter().find(|t| &t.id == type_ref) else {
        return Ok(None);
    };
    if !is_synthetic_id(&named.id) {
        return Ok(None);
    }
    // Borrow checker: any recursive call back into the renderer wants to walk
    // ctx.spec.types, so detach the NamedType before recursing.
    let named_clone = named.clone();
    let nested_name = pascal_case(prop_name);

    let body = match &named_clone.definition {
        TypeDef::Object(obj) if !obj.properties.is_empty() => {
            // Inline-promoted nested classes inherit visibility from their
            // enclosing class — no modifier emitted.
            render_object(ctx, &nested_name, "", &named_clone, obj, &[])?
        }
        TypeDef::EnumString(e) if e.values.len() > 1 => {
            render_enum_string(ctx, &nested_name, "", e, &[])?
        }
        TypeDef::EnumInt(e) => render_enum_int(ctx, &nested_name, "", e)?,
        // Inline object with no own properties (additionalProperties only),
        // inline single-value enum (always a `String` at the use site), or
        // anything else: fall back to the regular resolver.
        _ => return Ok(None),
    };
    nested_bodies.push(body);
    Ok(Some(nested_name))
}

fn pascal_case(input: &str) -> String {
    let mut out = String::with_capacity(input.len());
    let mut upper = true;
    for ch in input.chars() {
        if ch == '_' || ch == '-' || ch == ' ' {
            upper = true;
            continue;
        }
        if !ch.is_ascii_alphanumeric() {
            continue;
        }
        if upper {
            out.push(ch.to_ascii_uppercase());
            upper = false;
        } else {
            out.push(ch);
        }
    }
    if out.is_empty() {
        return "Nested".into();
    }
    if out.chars().next().map(|c| c.is_ascii_digit()).unwrap_or(false) {
        out.insert(0, '_');
    }
    out
}

// ---- enums ----

fn render_enum_string(
    ctx: &mut FileCtx,
    class_name: &str,
    vis: &str,
    e: &forge_plugin_sdk::ir::EnumStringType,
    fqcn_children: &[String],
) -> Result<String, RenderError> {
    ctx.imports.add("kotlinx.serialization.Serializable");
    let mut out = String::new();
    let _ = writeln!(out, "@Serializable");
    let last = e.values.len().saturating_sub(1);
    let _ = writeln!(out, "{vis}enum class {class_name} {{");
    for (i, v) in e.values.iter().enumerate() {
        let variant = enum_variant_ident(&v.value);
        let needs_serial_name = variant != v.value;
        // Within an enum class body, every variant gets a trailing comma —
        // Kotlin allows it on the last entry too and it matches the style of
        // the hand-written backend code we're aligning with. When the body
        // has additional members (functions, nested classes) we still need
        // a `;` after the variant list; emit comma-then-semicolon (legal
        // Kotlin) for that case.
        let suffix = match (i == last, fqcn_children.is_empty()) {
            (true, true) => ",",
            (true, false) => ";",
            _ => ",",
        };
        if needs_serial_name {
            ctx.imports.add("kotlinx.serialization.SerialName");
            let _ = writeln!(
                out,
                "    @SerialName(\"{}\") {variant}{suffix}",
                escape_kotlin_string(&v.value)
            );
        } else {
            let _ = writeln!(out, "    {variant}{suffix}");
        }
    }
    if !fqcn_children.is_empty() {
        write_indented_blocks(&mut out, fqcn_children);
    }
    out.push_str("}\n");
    Ok(out)
}

fn render_enum_int(
    ctx: &mut FileCtx,
    class_name: &str,
    vis: &str,
    e: &forge_plugin_sdk::ir::EnumIntType,
) -> Result<String, RenderError> {
    // kotlinx.serialization's enum support keys on the variant's @SerialName
    // string (or its Kotlin name), not on integers. To round-trip integer
    // enums through JSON numbers we emit a sealed-class-style wrapper plus a
    // custom KSerializer.
    ctx.imports.add("kotlinx.serialization.KSerializer");
    ctx.imports.add("kotlinx.serialization.Serializable");
    ctx.imports
        .add("kotlinx.serialization.descriptors.PrimitiveKind");
    ctx.imports
        .add("kotlinx.serialization.descriptors.PrimitiveSerialDescriptor");
    ctx.imports.add("kotlinx.serialization.encoding.Decoder");
    ctx.imports.add("kotlinx.serialization.encoding.Encoder");
    let (descriptor_kind, encode, decode, kt_ty) = match e.kind {
        forge_plugin_sdk::ir::IntKind::Int32 => ("INT", "encodeInt", "decodeInt", "Int"),
        forge_plugin_sdk::ir::IntKind::Int64 => ("LONG", "encodeLong", "decodeLong", "Long"),
    };

    let mut out = String::new();
    let _ = writeln!(
        out,
        "@Serializable(with = {class_name}.Serializer::class)\n\
         {vis}enum class {class_name}(val value: {kt_ty}) {{"
    );
    let last = e.values.len() - 1;
    for (i, v) in e.values.iter().enumerate() {
        let variant = enum_variant_ident(&format!("v{}", v.value));
        let _ = writeln!(
            out,
            "    {variant}({}{}){}",
            v.value,
            if matches!(e.kind, forge_plugin_sdk::ir::IntKind::Int64) {
                "L"
            } else {
                ""
            },
            if i == last { ",;" } else { "," }
        );
    }
    out.push('\n');
    let _ = writeln!(
        out,
        "    internal object Serializer : KSerializer<{class_name}> {{\n\
            \x20       override val descriptor = PrimitiveSerialDescriptor(\"{class_name}\", PrimitiveKind.{descriptor_kind})\n\
            \x20       override fun serialize(encoder: Encoder, value: {class_name}) = encoder.{encode}(value.value)\n\
            \x20       override fun deserialize(decoder: Decoder): {class_name} {{\n\
            \x20           val v = decoder.{decode}()\n\
            \x20           return entries.first {{ it.value == v }}\n\
            \x20       }}\n\
            \x20   }}"
    );
    out.push_str("}\n");
    Ok(out)
}

// ---- unions ----

fn render_union(
    ctx: &mut FileCtx,
    class_name: &str,
    vis: &str,
    _named: &NamedType,
    u: &UnionType,
    fqcn_children: &[String],
) -> Result<String, RenderError> {
    if let Some(disc) = effective_discriminator(ctx.spec, u) {
        return Ok(render_discriminated_union(
            ctx,
            class_name,
            vis,
            &disc,
            fqcn_children,
        ));
    }

    if any_variant_is_primitive(ctx.spec, u) {
        reject_nesting(class_name, "JsonElement typealias", fqcn_children)?;
        ctx.imports.add("kotlinx.serialization.json.JsonElement");
        return Ok(format!("{vis}typealias {class_name} = JsonElement\n"));
    }
    if let Some(sole) = single_object_variant(ctx.spec, u) {
        return render_single_variant_sealed(ctx, class_name, vis, sole, fqcn_children);
    }

    Err(RenderError::Unsupported(format!(
        "union type '{class_name}' has no discriminator and none could be inferred — \
         every variant must share exactly one property whose schema is a single-value \
         string enum (`type: string, const: \"<tag>\"`), or the union must contain a \
         primitive variant (rendered as JsonElement), or it must have exactly one \
         object variant (rendered as a single-member sealed interface)"
    )))
}

fn render_discriminated_union(
    ctx: &mut FileCtx,
    class_name: &str,
    vis: &str,
    disc: &crate::emit::EffectiveDiscriminator,
    fqcn_children: &[String],
) -> String {
    ctx.imports.add("kotlinx.serialization.Serializable");
    ctx.imports
        .add("kotlinx.serialization.json.JsonClassDiscriminator");
    let mut out = String::new();
    let _ = writeln!(
        out,
        "@OptIn(kotlinx.serialization.ExperimentalSerializationApi::class)"
    );
    let _ = writeln!(out, "@Serializable");
    let _ = writeln!(
        out,
        "@JsonClassDiscriminator(\"{}\")",
        escape_kotlin_string(&disc.property_name)
    );
    if fqcn_children.is_empty() {
        let _ = writeln!(out, "{vis}sealed interface {class_name}");
    } else {
        let _ = writeln!(out, "{vis}sealed interface {class_name} {{");
        write_indented_blocks(&mut out, fqcn_children);
        let _ = writeln!(out, "}}");
    }
    out
}

fn any_variant_is_primitive(spec: &Ir, u: &UnionType) -> bool {
    u.variants.iter().any(|v| {
        spec.types
            .iter()
            .find(|t| t.id == v.r#type)
            .map(|t| matches!(t.definition, TypeDef::Primitive(_) | TypeDef::Null))
            .unwrap_or(false)
    })
}

fn single_object_variant<'a>(spec: &'a Ir, u: &UnionType) -> Option<&'a NamedType> {
    if u.variants.len() != 1 {
        return None;
    }
    let variant_ref = &u.variants[0].r#type;
    let nt = spec.types.iter().find(|t| &t.id == variant_ref)?;
    matches!(nt.definition, TypeDef::Object(_)).then_some(nt)
}

fn render_single_variant_sealed(
    ctx: &mut FileCtx,
    class_name: &str,
    vis: &str,
    variant: &NamedType,
    fqcn_children: &[String],
) -> Result<String, RenderError> {
    // Under `missingExtensionPolicy = "warn"` the parent union can be
    // annotated while its sole variant isn't yet — surface that as a
    // recoverable render error rather than a wasm panic.
    let Some(variant_target) = ctx.index.get(variant.id.as_str()) else {
        return Err(RenderError::Unsupported(format!(
            "single-variant union '{class_name}' references unannotated variant '{}'; \
             add an x-kotlin-source to the variant or to the union to break the dependency",
            variant.id
        )));
    };
    let variant_class = variant_target.target.class_name.clone();
    let (variant_pkg, variant_wrappers) =
        split_phantom_wrappers(&variant_target.target.package, ctx.index);
    if variant_pkg != ctx.package {
        let mut fqcn = variant_pkg;
        for w in variant_wrappers.iter().rev() {
            fqcn.push('.');
            fqcn.push_str(w);
        }
        fqcn.push('.');
        fqcn.push_str(&variant_class);
        ctx.imports.add(fqcn);
    }
    ctx.imports.add("kotlinx.serialization.KSerializer");
    ctx.imports.add("kotlinx.serialization.Serializable");
    ctx.imports.add("kotlinx.serialization.encoding.Decoder");
    ctx.imports.add("kotlinx.serialization.encoding.Encoder");

    let mut out = String::new();
    let _ = writeln!(
        out,
        "@Serializable(with = {class_name}.Serializer::class)\n\
         {vis}sealed interface {class_name} {{\n\
            \x20   object Serializer : KSerializer<{class_name}> {{\n\
            \x20       private val delegate = {variant_class}.serializer()\n\
            \x20       override val descriptor = delegate.descriptor\n\
            \x20       override fun serialize(encoder: Encoder, value: {class_name}) =\n\
            \x20           delegate.serialize(encoder, value as {variant_class})\n\
            \x20       override fun deserialize(decoder: Decoder): {class_name} =\n\
            \x20           delegate.deserialize(decoder)\n\
            \x20   }}"
    );
    if !fqcn_children.is_empty() {
        out.push('\n');
        write_indented_blocks(&mut out, fqcn_children);
    }
    out.push_str("}\n");
    Ok(out)
}

// ---- array (typealias) ----

fn render_array_alias(
    ctx: &mut FileCtx,
    class_name: &str,
    vis: &str,
    named: &NamedType,
) -> Result<String, RenderError> {
    let TypeDef::Array(arr) = &named.definition else {
        unreachable!();
    };
    let inner = resolve_type(ctx, &arr.items)?;
    Ok(format!("{vis}typealias {class_name} = List<{inner}>\n"))
}

// ---- TypeRef → Kotlin type expression ----

fn resolve_type(ctx: &mut FileCtx, type_ref: &TypeRef) -> Result<String, RenderError> {
    // T | null → T?
    if let Some(inner) = types_ext::peel_nullable(&ctx.spec.types, type_ref) {
        let inner_kt = resolve_type(ctx, inner)?;
        if inner_kt.ends_with('?') {
            return Ok(inner_kt);
        }
        return Ok(format!("{inner_kt}?"));
    }

    if let Some(resolved) = ctx.index.get(type_ref.as_str()) {
        let (eff_pkg, wrappers) =
            split_phantom_wrappers(&resolved.target.package, ctx.index);
        if eff_pkg != ctx.package {
            // Walk through any phantom wrappers (outermost-first) so the
            // import targets the wrapper's nested-class path, e.g.
            // `ca.x.Group.Foo` for class Foo inside auto-wrapper Group.
            let mut fqcn = eff_pkg.clone();
            for w in wrappers.iter().rev() {
                fqcn.push('.');
                fqcn.push_str(w);
            }
            fqcn.push('.');
            fqcn.push_str(&resolved.target.class_name);
            ctx.imports.add(fqcn);
        }
        return Ok(resolved.target.class_name.clone());
    }

    let Some(named) = ctx.spec.types.iter().find(|t| &t.id == type_ref) else {
        return Err(RenderError::Unsupported(format!(
            "unresolved type reference '{type_ref}'"
        )));
    };

    match &named.definition {
        TypeDef::Primitive(p) => Ok(inline_primitive(ctx, p)),
        TypeDef::Array(a) => {
            let inner = resolve_type(ctx, &a.items)?;
            Ok(format!("List<{inner}>"))
        }
        TypeDef::Object(o) if o.properties.is_empty() => match &o.additional_properties {
            AdditionalProperties::Typed { r#type } => {
                let v = resolve_type(ctx, r#type)?;
                Ok(format!("Map<String, {v}>"))
            }
            AdditionalProperties::Any => {
                ctx.imports.add("kotlinx.serialization.json.JsonElement");
                Ok("Map<String, JsonElement>".into())
            }
            AdditionalProperties::Forbidden => {
                ctx.imports.add("kotlinx.serialization.json.JsonElement");
                Ok("JsonElement".into())
            }
        },
        TypeDef::Object(_) => Err(RenderError::Unsupported(format!(
            "synthetic object '{}' has properties but no x-kotlin-source; \
             add the extension to promote it to a named Kotlin class",
            named.id
        ))),
        TypeDef::EnumString(e) => {
            // Single-value string enums are how OAS expresses a literal
            // discriminator tag (`type: "dog"`). The sealed-interface
            // variant data class drops that property entirely — but if a
            // type still happens to reference it, inline as `String`.
            if e.values.len() == 1 {
                Ok("String".into())
            } else {
                Err(RenderError::Unsupported(format!(
                    "synthetic enum '{}' has multiple values but no x-kotlin-source; \
                     add the extension to promote it to a named Kotlin enum",
                    named.id
                )))
            }
        }
        TypeDef::EnumInt(_) | TypeDef::Union(_) => Err(RenderError::Unsupported(format!(
            "synthetic enum/union '{}' has no x-kotlin-source; \
             add the extension to promote it",
            named.id
        ))),
        TypeDef::Null => {
            // A bare `Null` typeref appearing outside `T | null` — model as
            // an always-null property by typing it as `Nothing?`.
            Ok("Nothing?".into())
        }
    }
}

fn inline_primitive(ctx: &mut FileCtx, p: &forge_plugin_sdk::ir::PrimitiveType) -> String {
    if matches!(p.kind, PrimitiveKind::String) {
        match p.constraints.format_extension.as_deref() {
            Some("date-time") => {
                return inline_with_serializer(ctx, SerKind::OffsetDateTime, "OffsetDateTime")
            }
            Some("instant") => return inline_with_serializer(ctx, SerKind::Instant, "Instant"),
            Some("date") => return inline_with_serializer(ctx, SerKind::LocalDate, "LocalDate"),
            Some("time") => return inline_with_serializer(ctx, SerKind::LocalTime, "LocalTime"),
            Some("uuid") => return inline_with_serializer(ctx, SerKind::Uuid, "UUID"),
            Some("byte") => {
                // ByteArray is a Kotlin builtin — no import needed. We DO need
                // the Base64 serializer + the @file:UseSerializers wiring so
                // kotlinx encodes inline `val x: ByteArray` as a Base64 JSON
                // string rather than the default JSON array of bytes.
                add_serializer_imports(ctx);
                ctx.serializers_to_emit.insert(SerKind::Base64Bytes);
                ctx.use_serializers.insert(SerKind::Base64Bytes);
                return "ByteArray".into();
            }
            _ => return "String".into(),
        }
    }
    match (p.kind, p.constraints.format_extension.as_deref()) {
        (PrimitiveKind::Integer, Some("int32")) => "Int".into(),
        (PrimitiveKind::Integer, _) => "Long".into(),
        (PrimitiveKind::Number, Some("float")) => "Float".into(),
        (PrimitiveKind::Number, _) => "Double".into(),
        (PrimitiveKind::Bool, _) => "Boolean".into(),
        (PrimitiveKind::String, _) => unreachable!(),
    }
}

/// Inline use of a JVM-shaped type (`java.time.OffsetDateTime`, `java.util.UUID`, …).
/// Adds the corresponding import, queues the serializer object for emission
/// at the end of the file, and wires `@file:UseSerializers` so every inline
/// property of the underlying type round-trips through the custom serializer
/// without a per-field `@Serializable(with = ...)` annotation.
fn inline_with_serializer(ctx: &mut FileCtx, kind: SerKind, kt: &'static str) -> String {
    let import = match kind {
        SerKind::OffsetDateTime => "java.time.OffsetDateTime",
        SerKind::Instant => "java.time.Instant",
        SerKind::LocalDate => "java.time.LocalDate",
        SerKind::LocalTime => "java.time.LocalTime",
        SerKind::Uuid => "java.util.UUID",
        SerKind::Base64Bytes => unreachable!("byte handled in inline_primitive"),
    };
    ctx.imports.add(import);
    add_serializer_imports(ctx);
    ctx.serializers_to_emit.insert(kind);
    ctx.use_serializers.insert(kind);
    kt.into()
}

/// Every inline `private object ___Serializer` we emit at the end of a file
/// uses these kotlinx.serialization types. The wrapped paths
/// (`render_value_object` / `render_byte_wrapper`) add them too — but inline
/// uses go through `inline_primitive` and need to opt in here.
fn add_serializer_imports(ctx: &mut FileCtx) {
    ctx.imports.add("kotlinx.serialization.KSerializer");
    ctx.imports
        .add("kotlinx.serialization.descriptors.PrimitiveKind");
    ctx.imports
        .add("kotlinx.serialization.descriptors.PrimitiveSerialDescriptor");
    ctx.imports.add("kotlinx.serialization.encoding.Decoder");
    ctx.imports.add("kotlinx.serialization.encoding.Encoder");
}

// ---- misc helpers ----

fn doc_block(named: &NamedType) -> Option<String> {
    let desc = named.description.as_deref()?;
    let mut out = String::from("/**\n");
    for line in desc.lines() {
        let _ = writeln!(out, " * {line}");
    }
    out.push_str(" */\n");
    Some(out)
}

fn escape_kotlin_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            '$' => out.push_str("\\$"),
            c => out.push(c),
        }
    }
    out
}

