//! Orchestrate file emission for the tower-based Rust client.
//!
//! Each dynamic file is built as a `proc_macro2::TokenStream`, parsed
//! into a `syn::File`, and unparsed via `prettyplease` to get
//! consistently-formatted Rust source. Static templates (`mod.rs`,
//! `runtime.rs`) ride along unchanged via `include_str!`.

use forge_plugin_sdk::ir;
use forge_plugin_sdk::{FileMode, GenerationOutput, OutputFile};
use proc_macro2::TokenStream;
use quote::{format_ident, quote};

use codegen_rust_serde::{diagnostics, models, naming};

use crate::operation_impl;

const MOD_RS: &str = include_str!("../templates/mod.rs.in");
const RUNTIME_RS: &str = include_str!("../templates/runtime.rs.in");

const GEN_HEADER: &str = "// Generated by openapi-forge — do not edit by hand.\n\n";

/// Outcome of a generation pass.
///
/// `Rejected` carries the diagnostics collected from
/// [`codegen_rust_serde::diagnostics::report_fatal`] sites — any
/// unmodellable type (bare `null`, unresolved `$ref`, multi-variant
/// non-recursive union, non-JSON request body) trips this. The
/// consumer plugin (e.g. `generator-rust-tower`) turns this into a
/// `StageError::Rejected` at its WIT entry point.
pub enum Outcome {
    Generated(GenerationOutput),
    Rejected(Vec<ir::Diagnostic>),
}

pub fn all(spec: &ir::Ir) -> Outcome {
    let mut files = vec![
        OutputFile {
            path: "mod.rs".into(),
            content: MOD_RS.as_bytes().to_vec(),
            mode: FileMode::Text,
        },
        OutputFile {
            path: "runtime.rs".into(),
            content: RUNTIME_RS.as_bytes().to_vec(),
            mode: FileMode::Text,
        },
        OutputFile {
            path: "models.rs".into(),
            content: render_file(models::render(spec)).into_bytes(),
            mode: FileMode::Text,
        },
        OutputFile {
            path: "operations/mod.rs".into(),
            content: render_file(operations_mod(spec)).into_bytes(),
            mode: FileMode::Text,
        },
    ];

    for op in &spec.operations {
        let snake = naming::snake_case(&op.id);
        files.push(OutputFile {
            path: format!("operations/{snake}.rs"),
            content: render_file(operation_impl::render(spec, op)).into_bytes(),
            mode: FileMode::Text,
        });
    }

    // `types::type_ref_to_rust` and `operation_impl::render_request_struct`
    // push into a thread-local sink. A *fatal* push (any unmodellable
    // type) flips a counter; if it's non-zero we hand the diagnostics
    // back as a `Rejected` outcome instead of writing files the consumer
    // would have to discard anyway.
    let diagnostics = diagnostics::drain();
    if diagnostics::take_fatal_count() > 0 {
        return Outcome::Rejected(diagnostics);
    }
    Outcome::Generated(GenerationOutput { files, diagnostics })
}

/// Build `operations/mod.rs`: a `pub mod <snake>;` per kept op plus
/// root-level `pub use` re-exports of each op's request struct, `Output`,
/// and `Error` so callers spell `gen::operations::ListPets` instead of
/// `gen::operations::list_pets::ListPets`.
fn operations_mod(spec: &ir::Ir) -> TokenStream {
    let mods: Vec<TokenStream> = spec
        .operations
        .iter()
        .map(|op| {
            let snake = format_ident!("{}", naming::snake_case(&op.id));
            quote! { pub mod #snake; }
        })
        .collect();
    let reexports: Vec<TokenStream> = spec
        .operations
        .iter()
        .map(|op| {
            let snake = format_ident!("{}", naming::snake_case(&op.id));
            let struct_name = format_ident!("{}", naming::pascal_case(&op.id));
            let output_name = format_ident!("{}Output", naming::pascal_case(&op.id));
            let error_name = format_ident!("{}Error", naming::pascal_case(&op.id));
            quote! { pub use self::#snake::{#struct_name, #output_name, #error_name}; }
        })
        .collect();
    quote! {
        #![allow(unused_imports)]

        #(#mods)*

        #(#reexports)*
    }
}

/// Token stream → formatted Rust source. Parses through `syn::File` so
/// we hard-fail on invalid emissions (better to surface "the generator
/// produced bad Rust" eagerly than to hand the consumer a file that won't
/// compile). The `// Generated by …` header is prepended in plain text
/// because `syn` doesn't model line comments.
fn render_file(tokens: TokenStream) -> String {
    let file: syn::File = syn::parse2(tokens).expect("generator produced invalid Rust");
    format!("{GEN_HEADER}{}", prettyplease::unparse(&file))
}
